## <center> DATA SCRAPING: INFOMATION OF DISNEY'S MOVIES <center>

#### IMPORT LIBRARIES

In [ ]:
from bs4 import BeautifulSoup
import requests

## TASK 1: GET DATA FROM AN EXAMPLE MOVIE 
### 1.1. Loading the webpage

In [ ]:
source = requests.get('https://en.wikipedia.org/wiki/Born_in_China')
webpage = BeautifulSoup(source.content)

# print(webpage.prettify)

#### 1.2. Movie Info Table

In [ ]:
info_table = webpage.find('table', class_ = 'infobox vevent').find_all('tr')

movie = {}

for index, row in enumerate(info_table):
   
  if index == 0:  # Movie title
    movie['Title'] = row.find('th').get_text()
  elif index == 1:  # Movie image
    continue
  else:  # Other infomation
    try:
      movie_key = row.find('th').get_text()
      movie_data = row.find('td').get_text()
      movie[movie_key] = movie_data
    except:
      continue

movie

{'Box office': '$25.1 million[4]',
 'Budget': '$5–10 million[3]',
 'Countries': 'United StatesChinaFrance',
 'Directed by': 'Lu Chuan',
 'Distributed by': 'Walt Disney Studios Motion PicturesShanghai Media Group (China)[2]',
 'Edited by': 'Matthew Meech',
 'Languages': 'EnglishMandarinFrench',
 'Music by': 'Barnaby Taylor',
 'Narrated by': 'John Krasinski (American release)Zhou Xun (Chinese release)Claire Keim (French release)',
 'Produced by': 'Roy ConliBrian LeithPhil Chapman',
 'Productioncompanies': '\nDisneynature\nShanghai Media Group\nChuan Films\nBrian Leith Productions[1]\n',
 'Release dates': '\nAugust\xa012,\xa02016\xa0(2016-08-12) (China)\nApril\xa021,\xa02017\xa0(2017-04-21) (United States)\nAugust\xa023,\xa02017\xa0(2017-08-23) (France)\n',
 'Running time': '76 minutes[2]',
 'Screenplay by': 'David FowlerBrian LeithPhil ChapmanLu Chuan',
 'Simplified': '我们诞生在中国',
 'Title': 'Born in China',
 'Traditional': '我們誕生在中國'}

There are some issues we should fix through html scraping:
  - The Box office and Released dates have wrong format for datetime and currency. 
  - There are references (eg. [1], [2]) that should be removed. 
  - The datetime is repeated in 2 different formats (June 12, 2010 (2010-06-12))
  - For a key having more than a paired value (eg. Starring), they should be listed.

In [ ]:
def clean_tag(row):
  '''
  Remove references and a datatime format (2010-06-12)
  '''
  if row.find('sup') or row.find('span', class_ = 'bday dtstart published updated'):
    for tag in row.find_all(['sup', 'span']):
      tag.decompose()



def get_list_data(row):
  
  ''' 
  To list the data if a key has more than a paired value
  '''

  if row.find('li'):
    return [li.get_text(' ', strip = True).replace('\xa0', ' ') for li in row.find_all('li')]

  elif row.find('br'):
    return [text.replace('\xa0', ' ') for text in row.stripped_strings]
  
  else:
    return row.get_text(' ', strip = True).replace('\xa0', ' ')



def get_movie_info(url):
  
  ''' 
  Get the movie infomation from the given url link 
  '''
  
  ### Loading the page
  source = requests.get(url)
  webpage = BeautifulSoup(source.content)

  info_table = webpage.find('table', class_ = 'infobox vevent').find_all('tr')


  ### Store the movie info
  movie = {}

  for index, row in enumerate(info_table):

    if index == 0:
      movie['Title'] = row.find('th').get_text(' ', strip = True)
    else:
      try:
        clean_tag(row)  # Clean tags
        movie_key = row.find('th').get_text(' ', strip = True)
        movie_data = get_list_data(row.find('td'))
        movie[movie_key] = movie_data
      except:
        continue

  return movie

In [ ]:
get_movie_info('https://en.wikipedia.org/wiki/Sister_Act_(franchise)#Sister_Act_3_(TBA)')

{'Created by': 'Paul Rudnick',
 'Film(s)': ['Sister Act',
  '(1992)',
  'Sister Act 2: Back in the Habit',
  '(1993)'],
 'Musical(s)': 'Sister Act',
 'Original work': 'Theatrical film',
 'Owner': ['Walt Disney Studios', '(', 'The Walt Disney Company', ')'],
 'Soundtrack(s)': ['Sister Act', 'Sister Act 2: Back in the Habit'],
 'Title': 'Sister Act'}

In [ ]:
a = get_movie_info('https://en.wikipedia.org/wiki/Born_in_China')
for key in a:
  print(key, ' : ', a[key])

Title  :  Born in China
Traditional  :  我們誕生在中國
Simplified  :  我们诞生在中国
Directed by  :  Lu Chuan
Screenplay by  :  ['David Fowler', 'Brian Leith', 'Phil Chapman', 'Lu Chuan']
Produced by  :  ['Roy Conli', 'Brian Leith', 'Phil Chapman']
Narrated by  :  ['John Krasinski', '(American release)', 'Zhou Xun', '(Chinese release)', 'Claire Keim', '(French release)']
Edited by  :  Matthew Meech
Music by  :  Barnaby Taylor
Production companies  :  ['Disneynature', 'Shanghai Media Group', 'Chuan Films', 'Brian Leith Productions']
Distributed by  :  ['Walt Disney Studios Motion Pictures', 'Shanghai Media Group', '(China)']
Release dates  :  ['August 12, 2016 (China)', 'April 21, 2017 (United States)', 'August 23, 2017 (France)']
Running time  :  76 minutes
Countries  :  ['United States', 'China', 'France']
Languages  :  ['English', 'Mandarin', 'French']
Budget  :  $5–10 million
Box office  :  $25.1 million

## TAKS 2: LIST OF DISNEY'S MOVIES
#### 2.1. Loading page

In [ ]:
source = requests.get('https://en.wikipedia.org/wiki/List_of_Walt_Disney_Pictures_films')
webpage = BeautifulSoup(source.content)

#### 2.2. Get relative movie's links and access the movie data

In [ ]:
movies = webpage.select('.wikitable.sortable i a')

base_path = 'https://en.wikipedia.org/'
movie_info_list = []


for index, movie in enumerate(movies):
  
  # if index == 6:
  #   break

  try:
    relative_path = movie['href']
    full_path = base_path + relative_path
    movie_info_list.append(get_movie_info(full_path))
  
  except Exception as e:
    print(e)
    print(movie.get_text())

'NoneType' object has no attribute 'find_all'
61
'NoneType' object has no attribute 'find_all'
Keeper of the Lost Cities
'NoneType' object has no attribute 'find_all'
Muppet Man
'NoneType' object has no attribute 'find_all'
The Thief
'NoneType' object has no attribute 'find_all'
Tom Sawyer
'NoneType' object has no attribute 'find_all'
Tower of Terror
'NoneType' object has no attribute 'find_all'
FC Barcelona
'NoneType' object has no attribute 'find_all'
Young Woman and the Sea

In [ ]:
print(len(movies))
print(len(movie_info_list))

534
526

The movies in the Exception list cannot be accessed to the infomation. This is because the attached links either do not exit or are not the true movie link (eg. its original novel, music, city, ect). In this case, we can skip them.

#### 2.3. Save and Reload movie data

In [ ]:
import json

def save_file(title, data):
  with open(title, 'w', encoding = 'utf-8') as f:
    json.dump(data, f, ensure_ascii = False, indent = 2)


save_file('disney_data.json', movie_info_list)

# ## This is for downloading files from Google colab jupiter to local system
from google.colab import files
files.download('disney_data.json')

## TASK 3: CLEANING UP DATA
#### 3.1. Uploading data

In [1]:
## This is for uploading files on Google Colab
import json

def load_data(title):
  with open(title, encoding = 'utf-8') as f:
    return json.load(f)


from google.colab import files
files.upload()

disney_data = load_data('disney_data.json')

Saving disney_data.json to disney_data.json

#### 3.2. Convert Running time into an integer

In [ ]:
## Let's check the Running format first.
[movie.get('Running time', 'N/A') for movie in disney_data]

## There are some movies that do not have the Running time infomation or have a list of Running time. In case there is a list, 
## we will take the first option

In [ ]:
import re

def convert_running_time(running_time):
  '''
  Convert running time by Regex library
  '''
  # If the movie does not have Running time
  if running_time == 'N/A':
    return None
  else:
    # If the Running time is a list
    if isinstance(running_time, list):
      strtime = re.search(r'(?P<strtime>\d{2,3}) (\w*)', running_time[0])
      return int(strtime.group('strtime'))
    else: # if the running time is a string
      strtime = re.search(r'(?P<strtime>\d{2,3}) (\w*)', running_time)
      return int(strtime.group('strtime'))

  
for movie in disney_data:
  movie['Running time'] = convert_running_time(movie.get('Running time', 'N/A'))

print([movie['Running time'] for movie in disney_data])

[41, 83, 88, 126, 74, 64, 70, 42, 70, 71, 75, 94, 73, 75, 82, 68, 74, 96, 75, 84, 77, 92, 69, 81, 60, 127, 93, 76, 75, 73, 85, 81, 70, 90, 80, 75, 83, 83, 72, 97, 75, 104, 93, 24, 105, 95, 97, 134, 24, 69, 92, 126, 79, 97, 128, 73, 91, 105, 98, 130, 89, 93, 67, 98, 100, 118, 103, 110, 80, 74, 91, 91, 97, 118, 139, 131, 92, 87, 116, 93, 110, 110, 131, 101, 108, 84, 78, 75, 164, 106, 110, 99, 113, 108, 102, 85, 91, 93, 100, 100, 79, 96, 113, 89, 117, 92, 88, 92, 87, 93, 93, 93, 90, 83, 96, 88, 89, 91, 93, 92, 97, 100, 100, 89, None, 91, 112, 115, 95, 91, 97, 104, 74, 48, 77, 104, 128, 101, 94, 104, 90, 100, 88, 93, 98, 112, 84, 97, 97, 114, 96, 97, 109, 83, 90, 107, 96, 103, 91, 95, 105, 113, 80, 101, 90, 74, 90, 89, 110, 74, 93, 84, 83, 74, 77, 107, 93, 88, 108, 84, 121, 89, 104, 90, 86, 84, 108, 107, 96, 98, 105, 108, 94, 106, 102, 88, 102, 102, 97, 111, 100, 96, 98, 78, 81, 108, 89, 99, 89, 81, 92, 100, 89, 79, 91, 101, 104, 103, 86, 105, 74, 93, 92, 98, 95, 93, 87, 93, 87, 128, 77, 86, 95, 114, 93, 83, 83, 88, 78, 112, 92, 78, 72, 82, 75, 104, 75, 113, 100, 78, 83, 69, 96, 115, 86, 92, 65, 99, 73, 73, 66, 128, 85, 88, 125, 96, 104, 95, 74, 72, 88, 75, 61, 117, 94, 100, 143, 96, 64, 87, 85, 86, 50, 74, 136, 76, 85, 65, 76, 40, 120, 84, 113, 65, 115, 67, 131, 100, 79, 68, 95, 97, 75, 100, 119, 100, 76, 68, 67, 120, 81, 143, 72, 118, 40, 72, 120, 99, 82, 117, 72, 150, 104, 73, 76, 92, 69, 70, 95, 94, 167, 111, 85, 82, 87, 110, 107, 124, 74, 82, 150, 97, 77, 91, 100, 112, 93, 78, 96, 99, 76, 98, 97, 99, 101, 96, None, 90, 101, 107, 82, 101, 96, 88, 97, 108, 104, 116, 103, 109, 115, 74, 79, 123, 108, 100, 125, None, 84, 90, 88, 109, 89, 104, 137, 106, 63, 88, 103, 93, 95, 132, 77, 96, 93, 104, 89, 87, 75, 101, 130, 77, 104, 149, 92, 81, 102, 125, 107, 78, 77, 124, 97, 84, 127, 81, 102, 124, 129, 76, 106, 82, 130, 95, 154, 97, 117, 108, 106, 99, 113, 97, 118, 103, 124, 107, 161, 80, 129, 76, 129, 102, None, 162, 114, 105, 109, 118, 104, 99, 112, 131, 112, 76, 128, 100, 118, 119, 104, 100, 104, 114, 99, 102, 107, 78, 86, 95, 160, 85, 100, 95, 115, 110, 122, 101, 121, 95, 107, 134, 95, 128, 102, 58, 108, 82, 157, 100, 107, 91, 84, None, None, None, None, None, None, None, None, 58, None, None, 102, None, 81, None, 70, None, None, 93, 91, 78, 85, 124, None, 83, None, None, None, 107, None, 79, 74, 468, 108, None]

In [ ]:
def convert_running_time_2(running_time):
  '''
  Convert running time use string.split. 
  It returns the same output as using Regex.
  '''
  # If the movie does not have Running time
  if running_time == 'N/A':
    return None
  else:
    # If the Running time is a list
    if isinstance(running_time, list):
      strtime = running_time[0].split(' ')[0]
      return int(strtime)
    else: # if the running time is a string
      strtime = running_time.split(' ')[0]
      return int(strtime.group('strtime'))

#### 3.3. Convert Budget into a number

In [ ]:
## Let's check the Budget first

[[movie.get('Budget', 'N/A'), movie['Title']] for movie in disney_data]

The budget current format makes things quite complicated. It includes the different currencies rather than US dollar, \$65 million or \$65,000,000, a range of value, a list and missing values 

So we will try on our best. We will substitute only US currency, other currency without the Dollar equivalent number is omitted. For the range of values and the list of values, we take the first number (eg. \$90-100 million ---> \$90 million )

In [ ]:
## Build function to convert Budget into floats

import re

def get_money_string(string):
  '''
  Return money string from a text
  '''
  
  if 'A$' in string or 'AU$' in string:
    return None

  if '$' not in string:
    return None
  
  else:
    string = string.lower()
    if 'million' in string or 'billion' in string:
      pattern = r'[US]*\$(?P<number>[0-9.]+)[0-9\-\$\s\w\W]* (?P<unit>million|billion)'
      money = re.search(pattern, string)
      return money.group('number') + ' ' + money.group('unit')
    
    else:
      pattern = r'\$([0-9.,]+)'
      money = re.search(pattern, string)
      return money.group(1)


def word_to_number(string):

  if string is not None:

    if 'million' in string:
      string = string.replace(' million', '')
      return float(string) * 1000000

    elif 'billion' in string:
      string = string.replace(' billion', '')
      return float(string) * 1000000000

    else:
      string = string.replace(',', '')
      return float(string)


def get_budget(string):
  '''
  To obtain the money string
  '''
  
  if string in ['N/A', '', 'unknown', 'Unknown']:
    return None
  
  ## If the Budget value is a list
  if isinstance(string, list):
    substring = [s for s in string if '$' in s][0]  # Take the first value
    money_string = get_money_string(substring)
    return word_to_number(money_string)
  
  ## If the Budget value is a string
  else:
    money_string = get_money_string(string)
    return word_to_number(money_string)

In [ ]:
## Let's check the functions

for movie in disney_data:
  try:
    movie['Budget_converted'] = get_budget(movie.get('Budget', 'N/A'))
  except Exception as e:
    print(e)
    print(movie['Title'], movie['Budget'])

'NoneType' object has no attribute 'group'
Ponyo ['¥', '3.4 billion', '(', 'US$', '34 million)']
list index out of range
Jagga Jasoos ['131 crore']

In [ ]:
## Alright, we only have to fix Ponyo and Jagga Jasoos movie

for movie in disney_data:
  if movie['Title'] == 'Ponyo':
    movie['Budget_converted'] = 34000000
  if movie['Title'] == 'Jagga Jasoos':
    movie['Budget_converted'] = None
  
  print([movie.get('Budget', 'N/A'), movie['Budget_converted']])

['N/A', None]
['$1.49 million', 1490000.0]
['$2.6 million', 2600000.0]
['$2.28 million', 2280000.0]
['$600,000', 600000.0]
['$950,000', 950000.0]
['$858,000', 858000.0]
['N/A', None]
['$788,000', 788000.0]
['N/A', None]
['$1.35 million', 1350000.0]
['$2.125 million', 2125000.0]
['N/A', None]
['$1.5 million', 1500000.0]
['$1.5 million', 1500000.0]
['N/A', None]
['$2.2 million', 2200000.0]
['$1,800,000', 1800000.0]
['$3 million', 3000000.0]
['N/A', None]
['$4 million', 4000000.0]
['$2 million', 2000000.0]
['$300,000', 300000.0]
['$1.8 million', 1800000.0]
['N/A', None]
['$5 million', 5000000.0]
['N/A', None]
['$4 million', 4000000.0]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['$700,000', 700000.0]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['$6 million', 6000000.0]
['under $1 million or $1,250,000', 1000000.0]
['N/A', None]
['N/A', None]
['$2 million', 2000000.0]
['N/A', None]
['N/A', None]
['$2.5 million', 2500000.0]
['N/A', None]
['N/A', None]
['N/A', None]
['$4 million', 4000000.0]
['$3.6 million', 3600000.0]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['$3 million', 3000000.0]
['N/A', None]
['$3 million', 3000000.0]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['$3 million', 3000000.0]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['$4.4–6 million', 4400000.0]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['$4 million', 4000000.0]
['N/A', None]
['$5 million', 5000000.0]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['$5 million', 5000000.0]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['$4 million', 4000000.0]
['N/A', None]
['N/A', None]
['N/A', None]
['$6.3 million', 6300000.0]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['$5 million', 5000000.0]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['$8 million', 8000000.0]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['AU$1 million', None]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['$5 million', 5000000.0]
['N/A', None]
['N/A', None]
['N/A', None]
['$7.5 million', 7500000.0]
['N/A', None]
['$10 million', 10000000.0]
['N/A', None]
['N/A', None]
['$3.5 to 4 million', 3500000.0]
['N/A', None]
['N/A', None]
['N/A', None]
['$5.25 million', 5250000.0]
['$20 million', 20000000.0]
['N/A', None]
['$9 million', 9000000.0]
['N/A', None]
['$6-8 million', 6000000.0]
['$20 million', 20000000.0]
['N/A', None]
['N/A', None]
['$18 million', 18000000.0]
['$12 million', 12000000.0]
['$14 million', 14000000.0]
['N/A', None]
['$17 million', 17000000.0]
['$5 million', 5000000.0]
['unknown', None]
['$20 million', 20000000.0]
['$11 million', 11000000.0]
['$28 million', 28000000.0]
['$44 million', 44000000.0]
['N/A', None]
['N/A', None]
['$14 million', 14000000.0]
['$9 million', 9000000.0]
['N/A', None]
['A$8.7 million', None]
['$31 million', 31000000.0]
['$18 million', 18000000.0]
['$5 million', 5000000.0]
['$40 million', 40000000.0]
['$20 million', 20000000.0]
['N/A', None]
['$14 million', 14000000.0]
['60 million Norwegian Kroner (around $8.7 million in 1989)', 8700000.0]
['N/A', None]
['$35-40 million', 35000000.0]
['$25 million', 25000000.0]
['$15 million', 15000000.0]
['$32 million', 32000000.0]
['$14 million', 14000000.0]
['$28 million', 28000000.0]
['$12 million', 12000000.0]
['N/A', None]
['N/A', None]
['$6.5 million', 6500000.0]
['$28 million', 28000000.0]
['$17 million', 17000000.0]
['$30 million', 30000000.0]
['N/A', None]
['$13 million', 13000000.0]
['N/A', None]
['N/A', None]
['$45 million', 45000000.0]
['$31 million', 31000000.0]
['N/A', None]
['$22 million', 22000000.0]
['$30 million', 30000000.0]
['N/A', None]
['$22 million', 22000000.0]
[['$32 million', '(estimated)'], 32000000.0]
['$18 million', 18000000.0]
['$55 million', 55000000.0]
['$24 million', 24000000.0]
['$15 million', 15000000.0]
['$12 million', 12000000.0]
['N/A', None]
['$30 million', 30000000.0]
['N/A', None]
['$31 million', 31000000.0]
['N/A', None]
['$38 million', 38000000.0]
['$70 million', 70000000.0]
['$15 million', 15000000.0]
['N/A', None]
['$67 million', 67000000.0]
['N/A', None]
['$32 million', 32000000.0]
['$7 million', 7000000.0]
['$85 million', 85000000.0]
['$55 million', 55000000.0]
['$3 million', 3000000.0]
['$16 million', 16000000.0]
['$80 million', 80000000.0]
['$30 million', 30000000.0]
['$24 million', 24000000.0]
['$90 million', 90000000.0]
['$15 million', 15000000.0]
['N/A', None]
['$30 million', 30000000.0]
['$120 million', 120000000.0]
['$90 million', 90000000.0]
['$65 million', 65000000.0]
['$5 million', 5000000.0]
['N/A', None]
['$130 million', 130000000.0]
['$75–90 million', 75000000.0]
['$10 million', 10000000.0]
['$90 million', 90000000.0]
['$15 million –$30 million', 15000000.0]
['$4,000,000 (estimated)', 4000000.0]
['$127.5 million', 127500000.0]
['$80–$85 million', 80000000.0]
['$65 million', 65000000.0]
['N/A', None]
['$30 million', 30000000.0]
['$85 million', 85000000.0]
['$100 million', 100000000.0]
['$23 million', 23000000.0]
['N/A', None]
['$90–120 million', 90000000.0]
['$26 million', 26000000.0]
['$25 million', 25000000.0]
['$115 million', 115000000.0]
['N/A', None]
['$33 million', 33000000.0]
['$20 million', 20000000.0]
['$5 million', 5000000.0]
['N/A', None]
['$22 million', 22000000.0]
['$80 million', 80000000.0]
['$35 million', 35000000.0]
['(US$15–19.2 million)', 15000000.0]
['$15 million', 15000000.0]
['$65 million', 65000000.0]
['$140 million', 140000000.0]
['N/A', None]
['$20 million', 20000000.0]
['$12 million', 12000000.0]
['$46 million', 46000000.0]
['$13 million', 13000000.0]
['$20 million', 20000000.0]
['$17 million', 17000000.0]
['$94 million', 94000000.0]
['$140 million', 140000000.0]
['$26 million', 26000000.0]
['N/A', None]
['N/A', None]
['$46 million', 46000000.0]
['$90 million', 90000000.0]
['N/A', None]
['$10 million', 10000000.0]
['$28 million', 28000000.0]
['N/A', None]
['$15 million', 15000000.0]
['N/A', None]
['$110 million', 110000000.0]
['N/A', None]
['$110 million', 110000000.0]
['N/A', None]
['$45 million', 45000000.0]
['N/A', None]
['$92–145 million', 92000000.0]
['N/A', None]
['$100 million', 100000000.0]
['N/A', None]
['N/A', None]
['$20 million', 20000000.0]
['$56 million', 56000000.0]
['$25 million', 25000000.0]
['N/A', None]
['$50 million', 50000000.0]
[['¥', '2.4 billion', 'US$24 million'], 24000000.0]
['$35 million', 35000000.0]
['$35 million', 35000000.0]
['N/A', None]
['N/A', None]
['$25 million', 25000000.0]
['$150 million', 150000000.0]
['$180 million', 180000000.0]
['N/A', None]
['$30 million', 30000000.0]
['$1 million', 1000000.0]
['N/A', None]
['$40 million', 40000000.0]
['$50 million', 50000000.0]
['$80 million', 80000000.0]
['$120 million', 120000000.0]
['N/A', None]
['$225 million', 225000000.0]
['$30 million', 30000000.0]
['N/A', None]
['$24 million', 24000000.0]
['$12 million', 12000000.0]
['N/A', None]
['$8 million', 8000000.0]
['$17 million', 17000000.0]
['$150 million', 150000000.0]
['$300 million', 300000000.0]
['$150 million', 150000000.0]
['N/A', None]
['$25 million', 25000000.0]
['N/A', None]
['$22 million', 22000000.0]
['$85 million', 85000000.0]
['$130 million', 130000000.0]
['$7 million', 7000000.0]
['$25 million', 25000000.0]
['$225 million', 225000000.0]
['$180 million', 180000000.0]
['N/A', None]
['$20 million', 20000000.0]
['N/A', None]
['$11 million', 11000000.0]
['N/A', None]
['$50 million', 50000000.0]
['$150 million', 150000000.0]
['$80 million', 80000000.0]
['N/A', None]
['$50 million', 50000000.0]
['$30 million', 30000000.0]
['$47 million', 47000000.0]
['N/A', None]
['$175 million', 175000000.0]
['N/A', None]
['$150 million', 150000000.0]
[['¥', '3.4 billion', '(', 'US$', '34 million)'], 34000000]
['N/A', None]
['$30—$35 million', 30000000.0]
['$8 million ( ₽ 350 million)', 8000000.0]
['$175–200 million', 175000000.0]
['$35 million', 35000000.0]
['$105 million', 105000000.0]
['$150 –$200 million', 150000000.0]
['$80 million', 80000000.0]
['$150–200 million', 150000000.0]
['$200 million', 200000000.0]
['$150 million', 150000000.0]
['$22 million', 22000000.0]
['N/A', None]
['$30—$35 million', 30000000.0]
['$35 million', 35000000.0]
['N/A', None]
['$260 million', 260000000.0]
['$170 million', 170000000.0]
['', None]
['N/A', None]
['N/A', None]
['$150 million', 150000000.0]
['N/A', None]
['$5 million', 5000000.0]
['$8 million', 8000000.0]
[['$410.6 million (gross)', '$378.5 million (net)'], 410600000.0]
['$200 million', 200000000.0]
['$30 million', 30000000.0]
['N/A', None]
['$45 million', 45000000.0]
['N/A', None]
['$23 million', 23000000.0]
[['$306.6 million (gross)', '$263.7 million (net)'], 306600000.0]
['$5 million', 5000000.0]
['N/A', None]
['$185 million', 185000000.0]
['$25 million', 25000000.0]
['N/A', None]
['$39 million', 39000000.0]
['$30—35 million', 30000000.0]
['$165 million', 165000000.0]
['$200 million', 200000000.0]
['N/A', None]
['$200 million', 200000000.0]
['$225–250 million', 225000000.0]
['$50 million', 50000000.0]
['N/A', None]
['$150 million', 150000000.0]
['$35 million', 35000000.0]
['$50 million', 50000000.0]
['N/A', None]
['$5 million', 5000000.0]
['$25 million', 25000000.0]
['$180–263 million', 180000000.0]
['$50 million', 50000000.0]
['(US$3.0 million)', 3000000.0]
['$28 million', 28000000.0]
['$165 million', 165000000.0]
['$50 million', 50000000.0]
['$17 million', 17000000.0]
['N/A', None]
['$84.21-95 million', 84210000.0]
['$5–10 million', 5000000.0]
['$180–190 million', 180000000.0]
['$175 million', 175000000.0]
['', None]
['$175–200 million', 175000000.0]
['$70–80 million', 70000000.0]
['$150 million', 150000000.0]
['$175–177 million', 175000000.0]
['N/A', None]
['$170 million', 170000000.0]
['$200 million', 200000000.0]
['$140 million', 140000000.0]
['$65 million', 65000000.0]
['$15 million', 15000000.0]
['$150–175 million', 150000000.0]
['', None]
['$8 million', 8000000.0]
['$160–255 million', 160000000.0]
['$5–10 million', 5000000.0]
['$230–320 million', 230000000.0]
['$175 million', 175000000.0]
['N/A', None]
[['131 crore'], None]
[['~$8 million', '₽', '370 million'], 8000000.0]
['$175–225 million', 175000000.0]
['$100–130 million', 100000000.0]
['$200 million', 200000000.0]
['$75 million', 75000000.0]
['$120–133 million', 120000000.0]
['$175 million', 175000000.0]
['$130 million', 130000000.0]
['$170 million', 170000000.0]
['N/A', None]
['$183 million', 183000000.0]
['$200 million', 200000000.0]
['$250–260 million', 250000000.0]
['$185 million', 185000000.0]
['$60 million', 60000000.0]
['N/A', None]
['$150 million', 150000000.0]
['$40 million', 40000000.0]
['$42 million', 42000000.0]
['$175–200 million', 175000000.0]
['N/A', None]
['N/A', None]
['N/A', None]
['$125 million', 125000000.0]
['$12.5 million (stage production)', 12500000.0]
['N/A', None]
['$24 million', 24000000.0]
['N/A', None]
['$200 million', 200000000.0]
['Unknown', None]
['$26 million', 26000000.0]
['$150 million', 150000000.0]
['₽ 650 million', None]
['N/A', None]
['$100 million+', 100000000.0]
['$100–200 million', 100000000.0]
['N/A', None]
['$200 million', 200000000.0]
['$120–150 million', 120000000.0]
['N/A', None]
['₽ 454 million', None]
['N/A', None]
['N/A', None]
['$175 million', 175000000.0]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['$11 million', 11000000.0]
['N/A', None]
['$28 million', 28000000.0]
['N/A', None]
['$858,000', 858000.0]
['$53.4 million', 53400000.0]
['N/A', None]
['$85 million', 85000000.0]
['$70 million', 70000000.0]
['$75–90 million', 75000000.0]
['$80 million', 80000000.0]
['$130 million', 130000000.0]
['N/A', None]
['$5 million', 5000000.0]
['N/A', None]
['N/A', None]
['N/A', None]
['$18 million or $25 million', 18000000.0]
['N/A', None]
['$4 million', 4000000.0]
['$3 million', 3000000.0]
['N/A', None]
['$35-40 million', 35000000.0]
['N/A', None]

#### 3.4. Convert Box Office into a number

In [ ]:
### Check Box Office format
[[movie['Title'], movie.get('Box office', 'N/A')] for movie in disney_data]

[['Academy Award Review of Walt Disney Cartoons', '$45.472'],
 ['Snow White and the Seven Dwarfs', '$418 million'],
 ['Pinocchio', '$164 million'],
 ['Fantasia', '$76.4–$83.3 million (United States and Canada)'],
 ['The Reluctant Dragon', '$960,000 (worldwide rentals)'],
 ['Dumbo', '>$1.3 million (est. United States/Canada rentals, 1941)'],
 ['Bambi', '$267.4 million'],
 ['Saludos Amigos', '$1.135 million (worldwide rentals)'],
 ['Victory Through Air Power', '$799,000'],
 ['The Three Caballeros', '$3.355 million (worldwide rentals)'],
 ['Make Mine Music', '$3.275 million (worldwide rentals)'],
 ['Song of the South', '$65 million'],
 ['Fun and Fancy Free', '$3.165 million (worldwide rentals)'],
 ['Melody Time', '$2.56 million (worldwide rentals)'],
 ['So Dear to My Heart',
  '$3.7 million (U.S. rental) $575,000 (foreign rental)'],
 ['The Adventures of Ichabod and Mr. Toad',
  '$1.625 million (worldwide rentals)'],
 ['Cinderella', '$182 million'],
 ['Treasure Island', '$4,100,000 (worldwide rentals)'],
 ['Alice in Wonderland',
  ['$2.4 million (1951, domestic)', '$3.5 million (1974, domestic)']],
 ['The Story of Robin Hood', '$2.1 million (US rentals)'],
 ['Peter Pan', '$87.4 million (United States and Canada)'],
 ['The Sword and the Rose', '$1 million (US)'],
 ['The Living Desert', '$2.6 million (US)'],
 ['Rob Roy: The Highland Rogue', 'N/A'],
 ['The Vanishing Prairie', '$1.75 million (US and Canadian rentals)'],
 ['20,000 Leagues Under the Sea', '$28.2 million'],
 ['Davy Crockett: King of the Wild Frontier', '$2,150,000 (US)'],
 ['Lady and the Tramp', '$187 million'],
 ['The African Lion', '$2.1 million (US)'],
 ['The Littlest Outlaw', '$1.6 million (US)'],
 ['The Great Locomotive Chase', '$1.7 million (US)'],
 ['Davy Crockett and the River Pirates', 'N/A'],
 ['Secrets of Life', 'N/A'],
 ['Westward Ho the Wagons!', '$2.75 million (US)'],
 ['Johnny Tremain', 'N/A'],
 ['Perri', '$1.75 million (US rentals)'],
 ['Old Yeller', '$6,250,000 (U.S./Canada rentals)'],
 ['The Light in the Forest', 'N/A'],
 ['White Wilderness', '$1.8 million (est. US/Canada rentals)'],
 ['Tonka', '$2.5 million (est. US/ Canada rentals)'],
 ['Sleeping Beauty', '$51.6 million (United States and Canada)'],
 ['The Shaggy Dog', '$12.3 million (US and Canada rentals)'],
 ["Darby O'Gill and the Little People",
  ['Original release',
   ':',
   '$2.6 million (est. US/ Canada rentals)',
   '1969 re-release',
   ':',
   '$2.3 million  (US/ Canada rentals)']],
 ['Zorro', 'N/A'],
 ['Third Man on the Mountain', '$1,700,000 (US/Canada rentals)'],
 ['Toby Tyler or 10 Weeks with a Circus', '$3,100,000 (US/Canada rentals)'],
 ['Kidnapped', 'N/A'],
 ['Pollyanna', '$3.75 million (US and Canadian rentals)'],
 ['Zorro', 'N/A'],
 ['Jungle Cat', '$2.3 million (US and Canadian rentals)'],
 ['Ten Who Dared', 'N/A'],
 ['Swiss Family Robinson', '$40 million'],
 ['101 Dalmatians', '$303 million'],
 ['The Absent-Minded Professor', '$25.4 million'],
 ['The Parent Trap', '$25.1 million'],
 ['Nikki: Wild Dog of the North', 'N/A'],
 ['Greyfriars Bobby', 'N/A'],
 ['Babes in Toyland', '$4.6 million (U.S./Canada rentals)'],
 ['Moon Pilot', '$3.5 million'],
 ['Bon Voyage!', '$5 million (rentals)'],
 ['Big Red', 'N/A'],
 ['Almost Angels', 'N/A'],
 ['The Legend of Lobo', 'N/A'],
 ['In Search of the Castaways', '$21,745,500'],
 ['Son of Flubber', '$22.1 million'],
 ['Miracle of the White Stallions', '$2,550,000 (US/ Canada)'],
 ['Savage Sam', '$3,000,000 (U.S./Canada)'],
 ['Summer Magic', '$4,350,000 (US/ Canada rentals)'],
 ['The Incredible Journey', '$4.2 million (US/Canada) (rentals)'],
 ['The Sword in the Stone', '$22.2 million (United States and Canada)'],
 ['A Tiger Walks', 'est. $1,600,000 (US/ Canada)'],
 ['The Misadventures of Merlin Jones', '$4,000,000 (US/ Canada)'],
 ['The Three Lives of Thomasina', '$2,250,000 (US/ Canada)'],
 ['The Moon-Spinners', 'est. $3,500,000 (US/ Canada)'],
 ['Mary Poppins', '$103.1 million'],
 ['Those Calloways', '$3,500,000 (US/ Canada rentals)'],
 ['Emil and the Detectives', '$1,275,000'],
 ["The Monkey's Uncle", '$4,000,000 (US/Canada rentals)'],
 ['That Darn Cat!', '$28,068,222'],
 ['The Ugly Dachshund', '$6.2 million (est. US/ Canada rentals)'],
 ['Lt. Robin Crusoe, U.S.N.', '$22,565,634'],
 ['The Fighting Prince of Donegal', 'N/A'],
 ['Follow Me, Boys!', '$16,207,116'],
 ['Monkeys, Go Home!', '$3,000,000 (US/ Canada)'],
 ['The Adventures of Bullwhip Griffin', '$1,900,000 (US/ Canada)'],
 ['The Gnome-Mobile', '$4,000,000 (US/ Canada)'],
 ['The Jungle Book', '$378 million'],
 ['Charlie, the Lonesome Cougar', 'N/A'],
 ['The Happiest Millionaire', '$5 million (U.S./Canada rentals)'],
 ["Blackbeard's Ghost", '$21,540,050'],
 ['The One and Only, Genuine, Original Family Band',
  '$2,250,000 (US/ Canada)'],
 ['Never a Dull Moment', '$4,150,000 (US/ Canada rentals)'],
 ['The Horse in the Gray Flannel Suit', '$3.3 million  (US/ Canada rentals)'],
 ['The Love Bug', '$51.3 million'],
 ['Smith!', '$1.3 million (US/ Canada rentals)'],
 ['Rascal', 'N/A'],
 ['The Computer Wore Tennis Shoes', '$5.5 million (US/ Canada rentals)'],
 ['King of the Grizzlies', 'N/A'],
 ['The Boatniks', '$18,607,492'],
 ['The Wild Country', '$4 million (rentals) (US/Canada)'],
 ['The Aristocats', '$191 million'],
 ['The Barefoot Executive', 'N/A'],
 ['Scandalous John', 'N/A'],
 ['The Million Dollar Duck', '$5.1 million (North America) (rentals)'],
 ['Bedknobs and Broomsticks', '$17.9 million'],
 ['The Biscuit Eater', 'N/A'],
 ["Now You See Him, Now You Don't", '$4,610,000 (US/Canada) (rentals)'],
 ['Napoleon and Samantha', 'N/A'],
 ['Run, Cougar, Run', 'N/A'],
 ['Snowball Express', '$6,100,000 (US/ Canada rentals)'],
 ["The World's Greatest Athlete", '$22,583,370'],
 ['Charley and the Angel', 'N/A'],
 ['One Little Indian', '$2 million'],
 ['Robin Hood', '$33 million'],
 ['Superdad', '$7 million (US/Canada rentals)'],
 ['Herbie Rides Again',
  ['$38,229,000 (US/Canada gross)', '$30.8 million (worldwide rentals)']],
 ['The Bears and I', '$4 million (rentals) (US/Canada)'],
 ['The Castaway Cowboy', 'N/A'],
 ['The Island at the Top of the World', '$10 million (US/Canada rentals)'],
 ['The Strongest Man in the World', '$6.6 million (US/Canada rentals)'],
 ['Escape to Witch Mountain', '$20,000,000'],
 ['The Apple Dumpling Gang', '$36,853,000'],
 ['One of Our Dinosaurs is Missing', '$5.5 million (North American rentals)'],
 ["The Best of Walt Disney's True-Life Adventures", 'N/A'],
 ['True-Life Adventures', 'N/A'],
 ['Ride a Wild Pony', 'N/A'],
 ['No Deposit, No Return', 'N/A'],
 ['Treasure of Matecumbe', 'N/A'],
 ['Gus', '$21,873,000'],
 ['The Shaggy D.A.', '$10.5 million (US and Canada rentals)'],
 ['Freaky Friday', '$36 million'],
 ['Escape from the Dark', 'N/A'],
 ['The Many Adventures of Winnie the Pooh', 'N/A'],
 ['A Tale of Two Critters', 'N/A'],
 ['The Rescuers', '$169 million'],
 ['Herbie Goes to Monte Carlo', '$29 million'],
 ["Pete's Dragon", '$36 –39.6 million'],
 ['Candleshoe', 'N/A'],
 ['Return from Witch Mountain', 'N/A'],
 ['The Cat from Outer Space', 'N/A'],
 ['Hot Lead and Cold Feet', 'N/A'],
 ['The North Avenue Irregulars', 'N/A'],
 ['The Apple Dumpling Gang Rides Again', '$20,931,111'],
 ['Unidentified Flying Oddball', '$4.475 million (US/Canada rentals )'],
 ['The Black Hole', ['$35.8 million']],
 ['Midnight Madness', '$2.9 million'],
 ['The Watcher in the Woods', '$5 million'],
 ['Herbie Goes Bananas', '$18 million'],
 ["The Last Flight of Noah's Ark", '$11 million'],
 ['Popeye', '$60 million'],
 ['The Devil and Max Devlin', '$16 million (USA)'],
 ['Amy', 'N/A'],
 ['Dragonslayer', '$14.1 million'],
 ['The Fox and the Hound', '$63.5 million'],
 ['Condorman', 'N/A'],
 ['Night Crossing', '$8 million'],
 ['Tron', '$50 million'],
 ['Tex', '$7.4 million'],
 ['Trenchcoat', '$4,304,286 (US)'],
 ['Something Wicked This Way Comes', '$8.4 million'],
 ['Never Cry Wolf', '$27.6 million'],
 ['Return to Oz', '$11.1 million (USA)'],
 ['The Black Cauldron', '$21.3 million'],
 ['The Journey of Natty Gann', '$9.7 million (U.S. and Canada only)'],
 ['One Magic Christmas', '$13 million'],
 ['The Great Mouse Detective', '$38.7 million'],
 ['Flight of the Navigator', '$18,564,613'],
 ['Benji the Hunted', '$22.3 million'],
 ['The Man from Snowy River II', '$13,687,027'],
 ['Oliver & Company', '>$121 million'],
 ['Honey, I Shrunk the Kids', '$222.7 million'],
 ['Cheetah', '$8,153,677 (United States)'],
 ['The Little Mermaid', ''],
 ['DuckTales the Movie: Treasure of the Lost Lamp', '$18.1 million'],
 ['The Rescuers Down Under', '$47.4 million'],
 ['White Fang', '$34.8 million'],
 ['Shipwrecked', '$15.1 million'],
 ["Wild Hearts Can't Be Broken", '$7.3 million'],
 ['The Rocketeer', '$46.7 million (USA)'],
 ['Beauty and the Beast', '$440.1 million'],
 ['Newsies', '$2.8 million'],
 ['Honey, I Blew Up the Kid', '$96 million'],
 ['The Mighty Ducks', '$50.8 million'],
 ['Aladdin', '$504.1 million'],
 ['The Muppet Christmas Carol', '$27.2 million'],
 ['Homeward Bound: The Incredible Journey', '$57 million'],
 ['A Far Off Place', '$12.9 million'],
 ['The Adventures of Huck Finn', '$24.1 million'],
 ['Hocus Pocus', '$45.4 million'],
 ['Cool Runnings', '$154.9 million'],
 ['The Three Musketeers', '$111 million'],
 ['Iron Will', '$21 million'],
 ['Blank Check', '$39 million'],
 ['D2: The Mighty Ducks', '$45.6 million'],
 ['White Fang 2: Myth of the White Wolf', '$8,878,839 (US)'],
 ['The Lion King', '$968.5 million'],
 ['Angels in the Outfield', '$50.2 million'],
 ["Squanto: A Warrior's Tale", '$3,337,685'],
 ['The Santa Clause', '$189.8 million'],
 ["Rudyard Kipling's The Jungle Book", '$70.7 million'],
 ['Heavyweights', '$17.6 million'],
 ['Man of the House', '$40,070,995'],
 ['Tall Tale', '$11 million'],
 ['A Goofy Movie', '$37.6 million'],
 ['Pocahontas', '$346.1 million'],
 ['Operation Dumbo Drop', '$24,670,346'],
 ["A Kid in King Arthur's Court", '$13.4 million (domestic)'],
 ['The Big Green', '$17.7 million'],
 ['Frank and Ollie', 'N/A'],
 ['Toy Story', '$373 million'],
 ['Tom and Huck', '$23.9 million (US)'],
 ['Muppet Treasure Island', '$34.3 million (North America)'],
 ['Homeward Bound II: Lost in San Francisco', '$32.7 million'],
 ['James and the Giant Peach', '$37.7 million'],
 ['The Hunchback of Notre Dame', '$325.3 million'],
 ['First Kid', '$26,465,920 (USA)'],
 ['D3: The Mighty Ducks', '$22.9 million'],
 ['101 Dalmatians', '$320.7 million'],
 ['That Darn Cat', '$18.3 million'],
 ['Jungle 2 Jungle', '$59.9 million'],
 ['Honey, We Shrunk Ourselves', 'N/A'],
 ['Hercules', '$252.7 million'],
 ['George of the Jungle', '$174.4 million'],
 ['Air Bud', '$27.8 million'],
 ['RocketMan', '$15.4 million'],
 ['Flubber', '$178 million'],
 ['Mr. Magoo', '$28.9 million'],
 ['Meet the Deedles', '$4.4 million'],
 ['Mulan', '$304.3 million'],
 ['The Parent Trap', '$92.1 million'],
 ["The Jungle Book: Mowgli's Story", 'N/A'],
 ["I'll Be Home for Christmas", '$12.2 million'],
 ["A Bug's Life", '$363.3 million'],
 ['Mighty Joe Young', '$50.6 million (US)'],
 ['My Favorite Martian', '$36.8 million'],
 ["Doug's 1st Movie", '$19.4 million'],
 ['Endurance', 'N/A'],
 ['Tarzan', '$448.2 million'],
 ['Inspector Gadget', '$134.4 million'],
 ['The Straight Story', '$6.2 million'],
 ['Toy Story 2', '$497.4 million'],
 ['The Tigger Movie', '$96.2 million'],
 ["Whispers: An Elephant's Tale", '$500,000 (USA) (30 November 2000)'],
 ['Dinosaur', '$349.8 million'],
 ['Fantasia 2000', '$90.9 million'],
 ['The Kid', '$110.3 million'],
 ['The Little Mermaid II: Return to the Sea', 'N/A'],
 ['Remember the Titans', '$136.8 million'],
 ['102 Dalmatians', '$183.6 million'],
 ["The Emperor's New Groove", '$169.6 million'],
 ["Recess: School's Out", '$44.5 million'],
 ["Lady and the Tramp II: Scamp's Adventure", 'N/A'],
 ['Atlantis: The Lost Empire', '$186.1 million'],
 ['The Princess Diaries', '$165.3 million'],
 ["Max Keeble's Big Move", '$18.6 million'],
 ['Monsters, Inc.', '$577.4 million'],
 ["Mickey's Magical Christmas: Snowed in at the House of Mouse", 'N/A'],
 ['Snow Dogs', '$115 million'],
 ['Return to Never Land', '$115.1 million'],
 ['Cinderella II: Dreams Come True', 'N/A'],
 ['The Hunchback of Notre Dame II', 'N/A'],
 ['The Rookie', '$80.7 million'],
 ['Lilo & Stitch', '$273.1 million'],
 ['The Country Bears', '$18 million'],
 ['Spirited Away', ''],
 ['Tuck Everlasting', '$19.3 million'],
 ['The Santa Clause 2', '$172.9 million'],
 ['Treasure Planet', '$110 million'],
 ["101 Dalmatians II: Patch's London Adventure", 'N/A'],
 ['The Jungle Book 2', '$135.7 million'],
 ['Inspector Gadget 2', 'N/A'],
 ["Piglet's Big Movie", '$62.9 million'],
 ['Ghosts of the Abyss', '$28.7 million'],
 ['Holes', '$71.4 million'],
 ['The Lizzie McGuire Movie', '$55.5 million'],
 ['Finding Nemo', '$940.3 million'],
 ['Pirates of the Caribbean: The Curse of the Black Pearl', '$654.3 million'],
 ['Freaky Friday', '$160.8 million'],
 ['Stitch! The Movie', 'N/A'],
 ['George of the Jungle 2', 'N/A'],
 ['Brother Bear', '$250.4 million'],
 ['The Haunted Mansion', '$182.3 million'],
 ['The Young Black Stallion', '$9,638,389'],
 ["Teacher's Pet", '$6.5 million'],
 ['Miracle', '$64.5 million'],
 ['The Lion King 1½', 'N/A'],
 ['Confessions of a Teenage Drama Queen', '$105.1 million'],
 ['Winnie the Pooh: Springtime with Roo', 'N/A'],
 ['Home on the Range', '$145.5 million'],
 ['Sacred Planet', '$1,108,356'],
 ['Around the World in 80 Days', '$72.2 million'],
 ["America's Heart and Soul", '$314,402'],
 ['The Princess Diaries 2: Royal Engagement', '$134.7 million'],
 ['Mickey, Donald, Goofy: The Three Musketeers', 'N/A'],
 ['The Incredibles', '$631.6 million'],
 ["Mickey's Twice Upon a Christmas", 'N/A'],
 ['National Treasure', '$347.5 million'],
 ['Aliens of the Deep', '$9 million'],
 ['Mulan II', 'N/A'],
 ["Pooh's Heffalump Movie", '$52.9 million'],
 ['The Pacifier', '$198.6 million'],
 ['Ice Princess', '$27.6 million'],
 ['Tarzan II', 'N/A'],
 ['Herbie: Fully Loaded', '$144.1 million'],
 ["Howl's Moving Castle", ['¥', '23.2 billion', 'US$236 million (worldwide)']],
 ['Sky High', '$86.4 million'],
 ['Valiant', '$61.7 million'],
 ['Lilo & Stitch 2: Stitch Has a Glitch', 'N/A'],
 ["Pooh's Heffalump Halloween Movie", 'N/A'],
 ['The Greatest Game Ever Played', '$15.4 million'],
 ['Chicken Little', '$314.4 million'],
 ['The Chronicles of Narnia: The Lion, the Witch and the Wardrobe',
  '$745 million'],
 ["Kronk's New Groove", 'N/A'],
 ['Glory Road', '$42.9 million'],
 ['Roving Mars', '$11 million'],
 ['Bambi II', '$35 Million'],
 ['Eight Below', '$120.5 million'],
 ['The Shaggy Dog', '$87.1 million'],
 ['The Wild', '$102.3 million'],
 ['Cars', '$462 million'],
 ['Leroy & Stitch', 'N/A'],
 ["Pirates of the Caribbean: Dead Man's Chest", '$1.066 billion'],
 ['Invincible', '$58.5 million'],
 ['Brother Bear 2', 'N/A'],
 ['The Nightmare Before Christmas', '$91.5 million'],
 ['The Santa Clause 3: The Escape Clause', '$110.8 million'],
 ['The Fox and the Hound 2', 'N/A'],
 ['Cinderella III: A Twist in Time', 'N/A'],
 ['Bridge to Terabithia', '$137.6 million'],
 ['Meet the Robinsons', '$169.3 million'],
 ["Pirates of the Caribbean: At World's End", '$960.9 million'],
 ['Ratatouille', '$623.7 million'],
 ['The Secret of the Magic Gourd', 'N/A'],
 ['Underdog', '$65.3 million'],
 ['The Pixar Story', 'N/A'],
 ['The Game Plan', '$146.6 million'],
 ['Enchanted', '$340.5 million'],
 ['National Treasure: Book of Secrets', '$459.2 million'],
 ['Hannah Montana and Miley Cyrus: Best of Both Worlds Concert',
  '$70.6 million'],
 ['College Road Trip', '$51.5 million'],
 ['The Chronicles of Narnia: Prince Caspian', '$419.7 million'],
 ['WALL-E', '$521.3 million'],
 ["The Little Mermaid 3: Ariel's Beginning", 'N/A'],
 ['Beverly Hills Chihuahua', '$149.3 million'],
 ['Morning Light', '$275,776'],
 ['High School Musical 3: Senior Year', '$252.9 million'],
 ['Roadside Romeo', '$2 million'],
 ['Tinker Bell', '$9.2 million'],
 ['Bolt', '$310 million'],
 ['Bedtime Stories', '$212.9 million'],
 ['Jonas Brothers: The 3D Concert Experience', '$23.1 million'],
 ['Race to Witch Mountain', '$106.4 million'],
 ['Hannah Montana: The Movie', '$155.5 million'],
 ['Earth', '$109 million'],
 ["The Boys: The Sherman Brothers' Story", '$55,513'],
 ['Up', '$735.1 million'],
 ['Hexe Lilli: Der Drache und das magische Buch', 'N/A'],
 ['G-Force', '$292.8 million'],
 ['Ponyo', 'US$ 204.8 million'],
 ['Walt & El Grupo', 'N/A'],
 ['Tinker Bell and the Lost Treasure', '$8,582,265'],
 ['Книга Мастеров', '$11.3 million'],
 ['A Christmas Carol', '$325 million'],
 ['Old Dogs', '$96.8 million'],
 ['The Princess and the Frog', '$271 million'],
 ['Alice in Wonderland', '$1.025 billion'],
 ['Oceans', '$82.7 million'],
 ['Prince of Persia: The Sands of Time', '$336.4 million'],
 ['Toy Story 3', '$1.067 billion'],
 ["The Sorcerer's Apprentice", '$215.3 million'],
 ['Tales from Earthsea', ''],
 ['The Crimson Wing: Mystery of the Flamingos', 'N/A'],
 ['Tinker Bell and the Great Fairy Rescue', '$10,872,752'],
 ['Secretariat', '$60.3 million'],
 ['Do Dooni Chaar', 'N/A'],
 ['Tangled', '$592.4 million'],
 ['Tron: Legacy', '$400.1 million'],
 ['Once Upon a Warrior', 'N/A'],
 ['Beverly Hills Chihuahua 2', '$29.6 million'],
 ['Lilly the Witch: The Journey to Mandolan', 'N/A'],
 ['Mars Needs Moms', '$39.2 million'],
 ['Zokkomon', 'N/A'],
 ['African Cats', '$30.9 million'],
 ['Prom', '$10.7 million'],
 ['Pirates of the Caribbean: On Stranger Tides', '$1.046 billion'],
 ['Cars 2', '$559.8 million'],
 ['Winnie the Pooh', '$50.1 million'],
 ['Spooky Buddies', 'N/A'],
 ['The Muppets', '$165.2 million'],
 ['Treasure Buddies', 'N/A'],
 ['Arrietty', '$146 million'],
 ['John Carter', '$284.1 million'],
 ['Chimpanzee', '$34.8 million'],
 ['Arjun: The Warrior Prince', 'N/A'],
 ['Brave', '$540.4 million'],
 ['The Odd Life of Timothy Green', '$56 million'],
 ['Beverly Hills Chihuahua 3: Viva la Fiesta!', '$12.2 million'],
 ['Frankenweenie', '$81.5 million'],
 ['Secret of the Wings', '$67.5 million'],
 ['Wreck-It Ralph', '$471.2 million'],
 ['Oz the Great and Powerful', '$493.3 million'],
 ['Wings of Life', 'N/A'],
 ['Monsters University', '$743.6 million'],
 ['The Lone Ranger', '$260.5 million'],
 ['Planes', '$239.3 million'],
 ['Super Buddies', 'N/A'],
 ['Frozen', '$1.280 billion'],
 ['Saving Mr. Banks', '$117.9 million'],
 ['Muppets Most Wanted', '$80.4 million'],
 ['The Pirate Fairy', '$64.9 million'],
 ['Bears', '$21.3 million'],
 ['Million Dollar Arm', '$40.2 million'],
 ['Maleficent', '$758.5 million'],
 ['Planes: Fire & Rescue', '$147 million'],
 ['Khoobsurat', 'est. (US$10 million)'],
 ['Alexander and the Terrible, Horrible, No Good, Very Bad Day',
  '$100.6 million'],
 ['Big Hero 6', '$657.9 million'],
 ['Into the Woods', '$213.1 million'],
 ['McFarland, USA', '$45.7 million'],
 ['Tinker Bell and the Legend of the NeverBeast',
  '$31.2 million (non-US box office)'],
 ['Cinderella', '$542.4 million'],
 ['Monkey Kingdom', '$17.1 million'],
 ['Tomorrowland', '$209 million'],
 ['Inside Out', '$858.8 million'],
 ['ABCD 2', 'est.'],
 ['The Good Dinosaur', '$332.2 million'],
 ['The Finest Hours', '$52.1 million'],
 ['Zootopia', '$1.024 billion'],
 ['The Jungle Book', '$966.6 million'],
 ['Tini: The Movie', '$17 million'],
 ['Alice Through the Looking Glass', '$299.5 million'],
 ['Finding Dory', '$1.029 billion'],
 ['The BFG', '$195.2 million'],
 ["Pete's Dragon", '$143.7 million'],
 ['Queen of Katwe', '$10.4 million'],
 ['Moana', '$645 million'],
 ['Dangal', 'est.'],
 ['March of the Penguins', '$127.4 million'],
 ['Beauty and the Beast', '$1.264 billion'],
 ['Born in China', '$25.1 million'],
 ['Pirates of the Caribbean: Dead Men Tell No Tales', '$794.9 million'],
 ['Cars 3', '$383.9 million'],
 ['Ghost of the Mountains', 'N/A'],
 ['Jagga Jasoos', '83 crore'],
 ['The Last Knight', ['$30.5 million', '₽', '1.731 billion']],
 ['Coco', '$807.8 million'],
 ['A Wrinkle in Time', '$132.7 million'],
 ['Incredibles 2', '$1.245 billion'],
 ['Christopher Robin', '$197.7 million'],
 ['The Nutcracker and the Four Realms', '$174 million'],

Similar to the Budget, we will try to convert the Box office into an integer. However, ff a movie has more than a value, we will take their sum instead of the first number

In [ ]:
def get_box_office(string):
  '''
  To obtain the Box office string
  '''
  
  if string in ['N/A', '', 'unknown', 'Unknown', 'est.']:
    return None


  ## If the Budget value is a list
  if isinstance(string, list):
    substrings = [s for s in string if '$' in s]

    box_office_list =[]
    for sub in substrings:
      money_string = get_money_string(sub)
      box_office_list.append(word_to_number(money_string))
    return sum(box_office_list)
  
  else:
    string = string.lower()
    ## If there are 2 revenues in a string
    if (string.count('$') > 1) and ('–' not in string): 
      pattern = r'[US]*\$[0-9.]+[0-9\-\$\s\w\W]* million|\$[0-9\,\.]+'
      box_office_list = []
      for sub in re.findall(pattern, string):
        box_office_list.append(word_to_number(sub.replace('$', '')))
      return sum(box_office_list)
    
    else:
      money_string = get_money_string(string)
      return word_to_number(money_string)

In [ ]:
for movie in disney_data:
  try:
    movie['BoxOffice_converted'] = get_box_office(movie.get('Box office', 'N/A'))
  except Exception as e:
    print(e)
    print(movie['Box office'], movie['Title'])

'NoneType' object has no attribute 'group'
US$ 204.8 million Ponyo

In [ ]:
## Alright, we only need to fix the Ponyo movie with the Box office of 204.8 million

for movie in disney_data:
  if movie['Title'] == 'Ponyo':
    movie['BoxOffice_converted'] = '204800000'
  # if movie['Title'] == 'Jagga Jasoos':
  #   movie['BoxOffice_converted'] = None

  print([movie.get('Box office', 'N/A'), movie['BoxOffice_converted']])

['$45.472', 45.472]
['$418 million', 418000000.0]
['$164 million', 164000000.0]
['$76.4–$83.3 million (United States and Canada)', 76400000.0]
['$960,000 (worldwide rentals)', 960000.0]
['>$1.3 million (est. United States/Canada rentals, 1941)', 1300000.0]
['$267.4 million', 267399999.99999997]
['$1.135 million (worldwide rentals)', 1135000.0]
['$799,000', 799000.0]
['$3.355 million (worldwide rentals)', 3355000.0]
['$3.275 million (worldwide rentals)', 3275000.0]
['$65 million', 65000000.0]
['$3.165 million (worldwide rentals)', 3165000.0]
['$2.56 million (worldwide rentals)', 2560000.0]
['$3.7 million (U.S. rental) $575,000 (foreign rental)', 4275000.0]
['$1.625 million (worldwide rentals)', 1625000.0]
['$182 million', 182000000.0]
['$4,100,000 (worldwide rentals)', 4100000.0]
[['$2.4 million (1951, domestic)', '$3.5 million (1974, domestic)'], 5900000.0]
['$2.1 million (US rentals)', 2100000.0]
['$87.4 million (United States and Canada)', 87400000.0]
['$1 million (US)', 1000000.0]
['$2.6 million (US)', 2600000.0]
['N/A', None]
['$1.75 million (US and Canadian rentals)', 1750000.0]
['$28.2 million', 28200000.0]
['$2,150,000 (US)', 2150000.0]
['$187 million', 187000000.0]
['$2.1 million (US)', 2100000.0]
['$1.6 million (US)', 1600000.0]
['$1.7 million (US)', 1700000.0]
['N/A', None]
['N/A', None]
['$2.75 million (US)', 2750000.0]
['N/A', None]
['$1.75 million (US rentals)', 1750000.0]
['$6,250,000 (U.S./Canada rentals)', 6250000.0]
['N/A', None]
['$1.8 million (est. US/Canada rentals)', 1800000.0]
['$2.5 million (est. US/ Canada rentals)', 2500000.0]
['$51.6 million (United States and Canada)', 51600000.0]
['$12.3 million (US and Canada rentals)', 12300000.0]
[['Original release', ':', '$2.6 million (est. US/ Canada rentals)', '1969 re-release', ':', '$2.3 million  (US/ Canada rentals)'], 4900000.0]
['N/A', None]
['$1,700,000 (US/Canada rentals)', 1700000.0]
['$3,100,000 (US/Canada rentals)', 3100000.0]
['N/A', None]
['$3.75 million (US and Canadian rentals)', 3750000.0]
['N/A', None]
['$2.3 million (US and Canadian rentals)', 2300000.0]
['N/A', None]
['$40 million', 40000000.0]
['$303 million', 303000000.0]
['$25.4 million', 25400000.0]
['$25.1 million', 25100000.0]
['N/A', None]
['N/A', None]
['$4.6 million (U.S./Canada rentals)', 4600000.0]
['$3.5 million', 3500000.0]
['$5 million (rentals)', 5000000.0]
['N/A', None]
['N/A', None]
['N/A', None]
['$21,745,500', 21745500.0]
['$22.1 million', 22100000.0]
['$2,550,000 (US/ Canada)', 2550000.0]
['$3,000,000 (U.S./Canada)', 3000000.0]
['$4,350,000 (US/ Canada rentals)', 4350000.0]
['$4.2 million (US/Canada) (rentals)', 4200000.0]
['$22.2 million (United States and Canada)', 22200000.0]
['est. $1,600,000 (US/ Canada)', 1600000.0]
['$4,000,000 (US/ Canada)', 4000000.0]
['$2,250,000 (US/ Canada)', 2250000.0]
['est. $3,500,000 (US/ Canada)', 3500000.0]
['$103.1 million', 103100000.0]
['$3,500,000 (US/ Canada rentals)', 3500000.0]
['$1,275,000', 1275000.0]
['$4,000,000 (US/Canada rentals)', 4000000.0]
['$28,068,222', 28068222.0]
['$6.2 million (est. US/ Canada rentals)', 6200000.0]
['$22,565,634', 22565634.0]
['N/A', None]
['$16,207,116', 16207116.0]
['$3,000,000 (US/ Canada)', 3000000.0]
['$1,900,000 (US/ Canada)', 1900000.0]
['$4,000,000 (US/ Canada)', 4000000.0]
['$378 million', 378000000.0]
['N/A', None]
['$5 million (U.S./Canada rentals)', 5000000.0]
['$21,540,050', 21540050.0]
['$2,250,000 (US/ Canada)', 2250000.0]
['$4,150,000 (US/ Canada rentals)', 4150000.0]
['$3.3 million  (US/ Canada rentals)', 3300000.0]
['$51.3 million', 51300000.0]
['$1.3 million (US/ Canada rentals)', 1300000.0]
['N/A', None]
['$5.5 million (US/ Canada rentals)', 5500000.0]
['N/A', None]
['$18,607,492', 18607492.0]
['$4 million (rentals) (US/Canada)', 4000000.0]
['$191 million', 191000000.0]
['N/A', None]
['N/A', None]
['$5.1 million (North America) (rentals)', 5100000.0]
['$17.9 million', 17900000.0]
['N/A', None]
['$4,610,000 (US/Canada) (rentals)', 4610000.0]
['N/A', None]
['N/A', None]
['$6,100,000 (US/ Canada rentals)', 6100000.0]
['$22,583,370', 22583370.0]
['N/A', None]
['$2 million', 2000000.0]
['$33 million', 33000000.0]
['$7 million (US/Canada rentals)', 7000000.0]
[['$38,229,000 (US/Canada gross)', '$30.8 million (worldwide rentals)'], 69029000.0]
['$4 million (rentals) (US/Canada)', 4000000.0]
['N/A', None]
['$10 million (US/Canada rentals)', 10000000.0]
['$6.6 million (US/Canada rentals)', 6600000.0]
['$20,000,000', 20000000.0]
['$36,853,000', 36853000.0]
['$5.5 million (North American rentals)', 5500000.0]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['$21,873,000', 21873000.0]
['$10.5 million (US and Canada rentals)', 10500000.0]
['$36 million', 36000000.0]
['N/A', None]
['N/A', None]
['N/A', None]
['$169 million', 169000000.0]
['$29 million', 29000000.0]
['$36 –39.6 million', 36000000.0]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['$20,931,111', 20931111.0]
['$4.475 million (US/Canada rentals )', 4475000.0]
[['$35.8 million'], 35800000.0]
['$2.9 million', 2900000.0]
['$5 million', 5000000.0]
['$18 million', 18000000.0]
['$11 million', 11000000.0]
['$60 million', 60000000.0]
['$16 million (USA)', 16000000.0]
['N/A', None]
['$14.1 million', 14100000.0]
['$63.5 million', 63500000.0]
['N/A', None]
['$8 million', 8000000.0]
['$50 million', 50000000.0]
['$7.4 million', 7400000.0]
['$4,304,286 (US)', 4304286.0]
['$8.4 million', 8400000.0]
['$27.6 million', 27600000.0]
['$11.1 million (USA)', 11100000.0]
['$21.3 million', 21300000.0]
['$9.7 million (U.S. and Canada only)', 9700000.0]
['$13 million', 13000000.0]
['$38.7 million', 38700000.0]
['$18,564,613', 18564613.0]
['$22.3 million', 22300000.0]
['$13,687,027', 13687027.0]
['>$121 million', 121000000.0]
['$222.7 million', 222700000.0]
['$8,153,677 (United States)', 8153677.0]
['', None]
['$18.1 million', 18100000.0]
['$47.4 million', 47400000.0]
['$34.8 million', 34800000.0]
['$15.1 million', 15100000.0]
['$7.3 million', 7300000.0]
['$46.7 million (USA)', 46700000.0]
['$440.1 million', 440100000.0]
['$2.8 million', 2800000.0]
['$96 million', 96000000.0]
['$50.8 million', 50800000.0]
['$504.1 million', 504100000.0]
['$27.2 million', 27200000.0]
['$57 million', 57000000.0]
['$12.9 million', 12900000.0]
['$24.1 million', 24100000.0]
['$45.4 million', 45400000.0]
['$154.9 million', 154900000.0]
['$111 million', 111000000.0]
['$21 million', 21000000.0]
['$39 million', 39000000.0]
['$45.6 million', 45600000.0]
['$8,878,839 (US)', 8878839.0]
['$968.5 million', 968500000.0]
['$50.2 million', 50200000.0]
['$3,337,685', 3337685.0]
['$189.8 million', 189800000.0]
['$70.7 million', 70700000.0]
['$17.6 million', 17600000.0]
['$40,070,995', 40070995.0]
['$11 million', 11000000.0]
['$37.6 million', 37600000.0]
['$346.1 million', 346100000.0]
['$24,670,346', 24670346.0]
['$13.4 million (domestic)', 13400000.0]
['$17.7 million', 17700000.0]
['N/A', None]
['$373 million', 373000000.0]
['$23.9 million (US)', 23900000.0]
['$34.3 million (North America)', 34300000.0]
['$32.7 million', 32700000.000000004]
['$37.7 million', 37700000.0]
['$325.3 million', 325300000.0]
['$26,465,920 (USA)', 26465920.0]
['$22.9 million', 22900000.0]
['$320.7 million', 320700000.0]
['$18.3 million', 18300000.0]
['$59.9 million', 59900000.0]
['N/A', None]
['$252.7 million', 252700000.0]
['$174.4 million', 174400000.0]
['$27.8 million', 27800000.0]
['$15.4 million', 15400000.0]
['$178 million', 178000000.0]
['$28.9 million', 28900000.0]
['$4.4 million', 4400000.0]
['$304.3 million', 304300000.0]
['$92.1 million', 92100000.0]
['N/A', None]
['$12.2 million', 12200000.0]
['$363.3 million', 363300000.0]
['$50.6 million (US)', 50600000.0]
['$36.8 million', 36800000.0]
['$19.4 million', 19400000.0]
['N/A', None]
['$448.2 million', 448200000.0]
['$134.4 million', 134400000.0]
['$6.2 million', 6200000.0]
['$497.4 million', 497400000.0]
['$96.2 million', 96200000.0]
['$500,000 (USA) (30 November 2000)', 500000.0]
['$349.8 million', 349800000.0]
['$90.9 million', 90900000.0]
['$110.3 million', 110300000.0]
['N/A', None]
['$136.8 million', 136800000.0]
['$183.6 million', 183600000.0]
['$169.6 million', 169600000.0]
['$44.5 million', 44500000.0]
['N/A', None]
['$186.1 million', 186100000.0]
['$165.3 million', 165300000.0]
['$18.6 million', 18600000.0]
['$577.4 million', 577400000.0]
['N/A', None]
['$115 million', 115000000.0]
['$115.1 million', 115100000.0]
['N/A', None]
['N/A', None]
['$80.7 million', 80700000.0]
['$273.1 million', 273100000.0]
['$18 million', 18000000.0]
['', None]
['$19.3 million', 19300000.0]
['$172.9 million', 172900000.0]
['$110 million', 110000000.0]
['N/A', None]
['$135.7 million', 135700000.0]
['N/A', None]
['$62.9 million', 62900000.0]
['$28.7 million', 28700000.0]
['$71.4 million', 71400000.0]
['$55.5 million', 55500000.0]
['$940.3 million', 940300000.0]
['$654.3 million', 654300000.0]
['$160.8 million', 160800000.0]
['N/A', None]
['N/A', None]
['$250.4 million', 250400000.0]
['$182.3 million', 182300000.0]
['$9,638,389', 9638389.0]
['$6.5 million', 6500000.0]
['$64.5 million', 64500000.0]
['N/A', None]
['$105.1 million', 105100000.0]
['N/A', None]
['$145.5 million', 145500000.0]
['$1,108,356', 1108356.0]
['$72.2 million', 72200000.0]
['$314,402', 314402.0]
['$134.7 million', 134700000.0]
['N/A', None]
['$631.6 million', 631600000.0]
['N/A', None]
['$347.5 million', 347500000.0]
['$9 million', 9000000.0]
['N/A', None]
['$52.9 million', 52900000.0]
['$198.6 million', 198600000.0]
['$27.6 million', 27600000.0]
['N/A', None]
['$144.1 million', 144100000.0]
[['¥', '23.2 billion', 'US$236 million (worldwide)'], 236000000.0]
['$86.4 million', 86400000.0]
['$61.7 million', 61700000.0]
['N/A', None]
['N/A', None]
['$15.4 million', 15400000.0]
['$314.4 million', 314400000.0]
['$745 million', 745000000.0]
['N/A', None]
['$42.9 million', 42900000.0]
['$11 million', 11000000.0]
['$35 Million', 35000000.0]
['$120.5 million', 120500000.0]
['$87.1 million', 87100000.0]
['$102.3 million', 102300000.0]
['$462 million', 462000000.0]
['N/A', None]
['$1.066 billion', 1066000000.0]
['$58.5 million', 58500000.0]
['N/A', None]
['$91.5 million', 91500000.0]
['$110.8 million', 110800000.0]
['N/A', None]
['N/A', None]
['$137.6 million', 137600000.0]
['$169.3 million', 169300000.0]
['$960.9 million', 960900000.0]
['$623.7 million', 623700000.0]
['N/A', None]
['$65.3 million', 65300000.0]
['N/A', None]
['$146.6 million', 146600000.0]
['$340.5 million', 340500000.0]
['$459.2 million', 459200000.0]
['$70.6 million', 70600000.0]
['$51.5 million', 51500000.0]
['$419.7 million', 419700000.0]
['$521.3 million', 521299999.99999994]
['N/A', None]
['$149.3 million', 149300000.0]
['$275,776', 275776.0]
['$252.9 million', 252900000.0]
['$2 million', 2000000.0]
['$9.2 million', 9200000.0]
['$310 million', 310000000.0]
['$212.9 million', 212900000.0]
['$23.1 million', 23100000.0]
['$106.4 million', 106400000.0]
['$155.5 million', 155500000.0]
['$109 million', 109000000.0]
['$55,513', 55513.0]
['$735.1 million', 735100000.0]
['N/A', None]
['$292.8 million', 292800000.0]
['US$ 204.8 million', '$204.8 million']
['N/A', None]
['$8,582,265', 8582265.0]
['$11.3 million', 11300000.0]
['$325 million', 325000000.0]
['$96.8 million', 96800000.0]
['$271 million', 271000000.0]
['$1.025 billion', 1024999999.9999999]
['$82.7 million', 82700000.0]
['$336.4 million', 336400000.0]
['$1.067 billion', 1067000000.0]
['$215.3 million', 215300000.0]
['', None]
['N/A', None]
['$10,872,752', 10872752.0]
['$60.3 million', 60300000.0]
['N/A', None]
['$592.4 million', 592400000.0]
['$400.1 million', 400100000.0]
['N/A', None]
['$29.6 million', 29600000.0]
['N/A', None]
['$39.2 million', 39200000.0]
['N/A', None]
['$30.9 million', 30900000.0]
['$10.7 million', 10700000.0]
['$1.046 billion', 1046000000.0]
['$559.8 million', 559800000.0]
['$50.1 million', 50100000.0]
['N/A', None]
['$165.2 million', 165200000.0]
['N/A', None]
['$146 million', 146000000.0]
['$284.1 million', 284100000.0]
['$34.8 million', 34800000.0]
['N/A', None]
['$540.4 million', 540400000.0]
['$56 million', 56000000.0]
['$12.2 million', 12200000.0]
['$81.5 million', 81500000.0]
['$67.5 million', 67500000.0]
['$471.2 million', 471200000.0]
['$493.3 million', 493300000.0]
['N/A', None]
['$743.6 million', 743600000.0]
['$260.5 million', 260500000.0]
['$239.3 million', 239300000.0]
['N/A', None]
['$1.280 billion', 1280000000.0]
['$117.9 million', 117900000.0]
['$80.4 million', 80400000.0]
['$64.9 million', 64900000.00000001]
['$21.3 million', 21300000.0]
['$40.2 million', 40200000.0]
['$758.5 million', 758500000.0]
['$147 million', 147000000.0]
['est. (US$10 million)', 10000000.0]
['$100.6 million', 100600000.0]
['$657.9 million', 657900000.0]
['$213.1 million', 213100000.0]
['$45.7 million', 45700000.0]
['$31.2 million (non-US box office)', 31200000.0]
['$542.4 million', 542400000.0]
['$17.1 million', 17100000.0]
['$209 million', 209000000.0]
['$858.8 million', 858800000.0]
['est.', None]
['$332.2 million', 332200000.0]
['$52.1 million', 52100000.0]
['$1.024 billion', 1024000000.0]
['$966.6 million', 966600000.0]
['$17 million', 17000000.0]
['$299.5 million', 299500000.0]
['$1.029 billion', 1028999999.9999999]
['$195.2 million', 195200000.0]
['$143.7 million', 143700000.0]
['$10.4 million', 10400000.0]
['$645 million', 645000000.0]
['est.', None]
['$127.4 million', 127400000.0]
['$1.264 billion', 1264000000.0]
['$25.1 million', 25100000.0]
['$794.9 million', 794900000.0]
['$383.9 million', 383900000.0]
['N/A', None]
['83 crore', None]
[['$30.5 million', '₽', '1.731 billion'], 30500000.0]
['$807.8 million', 807800000.0]
['$132.7 million', 132699999.99999999]
['$1.245 billion', 1245000000.0]
['$197.7 million', 197700000.0]
['$174 million', 174000000.0]
['$529.3 million', 529299999.99999994]
['$349.5 million', 349500000.0]
['$353.3 million', 353300000.0]
['$7.7\n million', 7700000.0]
['', None]
['$1.073 billion', 1073000000.0]
['$1.663 billion', 1663000000.0]
['$491.7 million', 491700000.0]
['N/A', None]
['N/A', None]
['$1.450 billion', 1450000000.0]
['N/A', None]
['N/A', None]
['$141.9 million', 141900000.0]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['$70 million', 70000000.0]
['N/A', None]
['N/A', None]
['$121 million', 121000000.0]
[['₽ 2.046 billion', '$28.3 million (Worldwide)', '$28.6 million (Russia/ CIS )'], 56900000.0]
['N/A', None]
['$130.4 million', 130400000.0]
['$233.5 million', 233500000.0]
['$49.8 million', 49800000.0]
['$220.9 million', 220900000.0]
['$254.6 million', 254600000.0]
['N/A', None]
[['₽ 2.196 billion', '$27 million'], 27000000.0]
['N/A', None]
['N/A', None]
['$16.7 million', 16700000.0]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['N/A', None]
['$240 million', 240000000.0]
['N/A', None]
['$100.6 million', 100600000.0]
['N/A', None]
['$267.4 million', 267399999.99999997]
['N/A', None]
['N/A', None]
['$252.7 million', 252700000.0]
['$325.3 million', 325300000.0]
['$134.4 million', 134400000.0]
['$273.1 million', 273100000.0]
['$459.2 million', 459200000.0]
['N/A', None]
['$33 million', 33000000.0]
['N/A', None]
['N/A', None]
['N/A', None]
['$9,697,739 (USA)', 9697739.0]
['N/A', None]
['$191 million', 191000000.0]
['$22.2 million (United States and Canada)', 22200000.0]
['N/A', None]
['$46.7 million (USA)', 46700000.0]
['N/A', None]

#### 3.5. Convert datetime format

In [2]:
## Get release dates

[[movie.get('Release dates', 'N/A'), movie.get('Release date', 'N/A'), movie['Title']] for movie in disney_data]

[['N/A', ['May 19, 1937'], 'Academy Award Review of Walt Disney Cartoons'],
 [['December 21, 1937 ( Carthay Circle Theatre )',
   'February 4, 1938 (United States)'],
  'N/A',
  'Snow White and the Seven Dwarfs'],
 [['February 7, 1940 ( Center Theatre )', 'February 23, 1940 (United States)'],
  'N/A',
  'Pinocchio'],
 ['N/A', ['November 13, 1940'], 'Fantasia'],
 ['N/A', ['June 27, 1941'], 'The Reluctant Dragon'],
 [['October 23, 1941 (New York City)', 'October 31, 1941 (U.S.)'],
  'N/A',
  'Dumbo'],
 [['August 9, 1942 (World Premiere – London)',
   'August 13, 1942 (Premiere – New York City)',
   'August 21, 1942 (U.S.)'],
  'N/A',
  'Bambi'],
 [['August 24, 1942 (World Premiere – Rio de Janeiro)',
   'February 6, 1943 (U.S. Premiere – Boston)',
   'February 19, 1943 (U.S.)'],
  'N/A',
  'Saludos Amigos'],
 ['N/A', ['July 17, 1943'], 'Victory Through Air Power'],
 [['December 21, 1944 (Mexico City)', 'February 3, 1945 (US)'],
  'N/A',
  'The Three Caballeros'],
 [['April 20, 1946 (New York City premiere)', 'August 15, 1946 (U.S.)'],
  'N/A',
  'Make Mine Music'],
 [['November 12, 1946 (Premiere: Atlanta, Georgia)',
   'November 20, 1946',
   'March 30, 1947 (Stanford theater, Palo Alto, California)'],
  'N/A',
  'Song of the South'],
 ['N/A', ['September 27, 1947'], 'Fun and Fancy Free'],
 ['N/A', 'May 27, 1948', 'Melody Time'],
 [['November 29, 1948 (Chicago, Illinois)',
   'January 19, 1949 (Indianapolis, Indiana)'],
  'N/A',
  'So Dear to My Heart'],
 ['N/A', ['October 5, 1949'], 'The Adventures of Ichabod and Mr. Toad'],
 [['February 15, 1950 (Boston)', 'March 4, 1950 (United States)'],
  'N/A',
  'Cinderella'],
 [['June 22, 1950 (World Premiere-London)', 'July 30, 1950 (US)'],
  'N/A',
  'Treasure Island'],
 [['July 26, 1951 (London, premiere)',
   'July 28, 1951 (New York City, premiere)',
   'September 14, 1951 (United States)'],
  'N/A',
  'Alice in Wonderland'],
 [['March 13, 1952 (Premiere- London )', 'June 26, 1952 ( US )'],
  'N/A',
  'The Story of Robin Hood'],
 ['N/A', ['February 5, 1953 (United States)'], 'Peter Pan'],
 ['N/A', ['July 23, 1953 (US)'], 'The Sword and the Rose'],
 ['N/A', ['November 10, 1953'], 'The Living Desert'],
 [['26 October 1953 (Premiere- London )', '27 February 1954 ( US )'],
  'N/A',
  'Rob Roy: The Highland Rogue'],
 ['N/A', ['August 17, 1954'], 'The Vanishing Prairie'],
 ['N/A', ['December 23, 1954'], '20,000 Leagues Under the Sea'],
 ['N/A', 'May 25, 1955', 'Davy Crockett: King of the Wild Frontier'],
 ['N/A', ['June 22, 1955'], 'Lady and the Tramp'],
 ['N/A', ['September 14, 1955'], 'The African Lion'],
 ['N/A', 'December 22, 1955', 'The Littlest Outlaw'],
 ['N/A', 'June 8, 1956', 'The Great Locomotive Chase'],
 ['N/A', 'July 18, 1956', 'Davy Crockett and the River Pirates'],
 ['N/A', ['September 4, 1956'], 'Secrets of Life'],
 ['N/A', ['December 20, 1956'], 'Westward Ho the Wagons!'],
 ['N/A', 'June 19, 1957', 'Johnny Tremain'],
 ['N/A', 'August 28, 1957', 'Perri'],
 ['N/A', ['December 25, 1957'], 'Old Yeller'],
 ['N/A', ['July 8, 1958'], 'The Light in the Forest'],
 ['N/A', ['August 12, 1958'], 'White Wilderness'],
 ['N/A', ['December 25, 1958'], 'Tonka'],
 ['N/A', ['January 29, 1959'], 'Sleeping Beauty'],
 ['N/A', ['March 19, 1959'], 'The Shaggy Dog'],
 [['June 24, 1959 (Dublin)', 'June 26, 1959 (Los Angeles)'],
  'N/A',
  "Darby O'Gill and the Little People"],
 ['N/A', 'N/A', 'Zorro'],
 ['N/A', ['November 10, 1959'], 'Third Man on the Mountain'],
 ['N/A',
  'January 21, 1960 ( Sarasota, FL )',
  'Toby Tyler or 10 Weeks with a Circus'],
 ['N/A', ['February 24, 1960'], 'Kidnapped'],
 ['N/A', 'May 19, 1960', 'Pollyanna'],
 ['N/A', 'N/A', 'Zorro'],
 [['June 1960 ( Berlin )', 'August 10, 1960 (US)'], 'N/A', 'Jungle Cat'],
 ['N/A', ['November 1, 1960'], 'Ten Who Dared'],
 ['N/A', ['December 21, 1960'], 'Swiss Family Robinson'],
 ['N/A', ['January 25, 1961'], '101 Dalmatians'],
 ['N/A', 'March 16, 1961', 'The Absent-Minded Professor'],
 ['N/A', ['June 21, 1961'], 'The Parent Trap'],
 ['N/A', ['July 12, 1961'], 'Nikki: Wild Dog of the North'],
 ['N/A', ['July 17, 1961'], 'Greyfriars Bobby'],
 ['N/A', ['December 14, 1961'], 'Babes in Toyland'],
 ['N/A', 'April 5, 1962', 'Moon Pilot'],
 ['N/A', ['May 17, 1962'], 'Bon Voyage!'],
 ['N/A', ['June 6, 1962'], 'Big Red'],
 ['N/A', 'September 26, 1962', 'Almost Angels'],
 ['N/A', ['November 7, 1962 (Los Angeles)'], 'The Legend of Lobo'],
 [['November 14, 1962 (London, premiere)', 'December 19, 1962 (US)'],
  'N/A',
  'In Search of the Castaways'],
 ['N/A', ['January 16, 1963'], 'Son of Flubber'],
 ['N/A', ['March 29, 1963 (U.S.)'], 'Miracle of the White Stallions'],
 ['N/A', ['June 1, 1963'], 'Savage Sam'],
 ['N/A', ['July 7, 1963'], 'Summer Magic'],
 ['N/A', 'November 20, 1963', 'The Incredible Journey'],
 ['N/A', ['December 25, 1963'], 'The Sword in the Stone'],
 ['N/A', ['March 12, 1964'], 'A Tiger Walks'],
 ['N/A',
  ['February 11, 1964 (Los Angeles)'],
  'The Misadventures of Merlin Jones'],
 [['11 December 1963 ( New York City )', '4 June 1964 (U.S.)'],
  'N/A',
  'The Three Lives of Thomasina'],
 ['N/A', ['July 2, 1964'], 'The Moon-Spinners'],
 [['August 27, 1964 (LA)', 'September 24, 1964 (NY)'], 'N/A', 'Mary Poppins'],
 ['N/A', 'November 10, 1964', 'Those Calloways'],
 ['N/A', ['December 18, 1964'], 'Emil and the Detectives'],
 ['N/A', ['August 18, 1965 (Los Angeles)'], "The Monkey's Uncle"],
 ['N/A', ['December 2, 1965'], 'That Darn Cat!'],
 [['February 4, 1966 (premiere)', 'February 16, 1966 (United States)'],
  'N/A',
  'The Ugly Dachshund'],
 [['June 25, 1966 (San Diego)', 'June 29, 1966 (U.S.)'],
  'N/A',
  'Lt. Robin Crusoe, U.S.N.'],
 ['N/A', 'October 1, 1966', 'The Fighting Prince of Donegal'],
 ['N/A', ['December 1, 1966'], 'Follow Me, Boys!'],
 ['N/A', ['February 8, 1967 (San Francisco)'], 'Monkeys, Go Home!'],
 ['N/A', ['June 15, 1967'], 'The Adventures of Bullwhip Griffin'],
 ['N/A', ['July 12, 1967'], 'The Gnome-Mobile'],
 ['N/A', ['October 18, 1967'], 'The Jungle Book'],
 ['N/A', ['October 19, 1967'], 'Charlie, the Lonesome Cougar'],
 [['June 23, 1967', 'November 30, 1967'], 'N/A', 'The Happiest Millionaire'],
 ['N/A', ['February 8, 1968'], "Blackbeard's Ghost"],
 ['N/A',
  ['March 21, 1968 ( Radio City Music Hall )'],
  'The One and Only, Genuine, Original Family Band'],
 ['N/A', ['June 26, 1968'], 'Never a Dull Moment'],
 ['N/A', ['December 3, 1968'], 'The Horse in the Gray Flannel Suit'],
 [['December 24, 1968 (limited)', 'March 13, 1969 (wide)'],
  'N/A',
  'The Love Bug'],
 ['N/A', ['March 21, 1969'], 'Smith!'],
 ['N/A', ['June 11, 1969'], 'Rascal'],
 ['N/A', ['November 28, 1969'], 'The Computer Wore Tennis Shoes'],
 ['N/A', ['February 11, 1970'], 'King of the Grizzlies'],
 ['N/A', 'July 1, 1970', 'The Boatniks'],
 [['December 15, 1970', 'January 20, 1971'], 'N/A', 'The Wild Country'],
 [['December 11, 1970 (premiere)', 'December 24, 1970 (United States)'],
  'N/A',
  'The Aristocats'],
 ['N/A', 'March 17, 1971', 'The Barefoot Executive'],
 ['N/A', 'June 22, 1971', 'Scandalous John'],
 ['N/A', ['June 30, 1971'], 'The Million Dollar Duck'],
 ['N/A', ['October 7, 1971'], 'Bedknobs and Broomsticks'],
 ['N/A', ['March 22, 1972 (US)'], 'The Biscuit Eater'],
 ['N/A', 'July 12, 1972', "Now You See Him, Now You Don't"],
 ['N/A', ['July 5, 1972'], 'Napoleon and Samantha'],
 ['N/A', ['October 18, 1972'], 'Run, Cougar, Run'],
 ['N/A', ['December 22, 1972'], 'Snowball Express'],
 ['N/A', 'February 1, 1973', "The World's Greatest Athlete"],
 ['N/A', ['March 23, 1973'], 'Charley and the Angel'],
 ['N/A', ['June 20, 1973'], 'One Little Indian'],
 ['N/A', ['November 8, 1973'], 'Robin Hood'],
 ['N/A', ['December 14, 1973'], 'Superdad'],
 ['N/A', ['June 6, 1974'], 'Herbie Rides Again'],
 ['N/A', ['July 31, 1974'], 'The Bears and I'],
 ['N/A', ['August 1, 1974'], 'The Castaway Cowboy'],
 ['N/A',
  'December 20, 1974 (with Winnie the Pooh and Tigger Too )',
  'The Island at the Top of the World'],
 ['N/A', ['February 6, 1975'], 'The Strongest Man in the World'],
 ['N/A', ['March 21, 1975 (United States)'], 'Escape to Witch Mountain'],
 ['N/A', ['July 1, 1975'], 'The Apple Dumpling Gang'],
 ['N/A', ['July 9, 1975'], 'One of Our Dinosaurs is Missing'],
 ['N/A',
  ['October 8, 1975'],
  "The Best of Walt Disney's True-Life Adventures"],
 ['N/A', ['1948–1960'], 'True-Life Adventures'],
 ['N/A', 'December 25, 1975', 'Ride a Wild Pony'],
 ['N/A', ['February 11, 1976 (Los Angeles)'], 'No Deposit, No Return'],
 ['N/A', ['July 1, 1976'], 'Treasure of Matecumbe'],
 ['N/A', ['July 7, 1976'], 'Gus'],
 ['N/A', ['December 16, 1976'], 'The Shaggy D.A.'],
 ['N/A', ['December 17, 1976'], 'Freaky Friday'],
 [['May 26, 1976', '(UK)', 'March 11, 1977', '(US)'],
  'N/A',
  'Escape from the Dark'],
 ['N/A', ['March 11, 1977'], 'The Many Adventures of Winnie the Pooh'],
 ['N/A', ['June 20, 1977'], 'A Tale of Two Critters'],
 ['N/A', ['June 22, 1977'], 'The Rescuers'],
 ['N/A', ['June 24, 1977'], 'Herbie Goes to Monte Carlo'],
 ['N/A', ['November 3, 1977'], "Pete's Dragon"],
 ['N/A', 'December 16, 1977', 'Candleshoe'],
 ['N/A', ['March 10, 1978'], 'Return from Witch Mountain'],
 ['N/A', ['June 30, 1978 (New York)'], 'The Cat from Outer Space'],
 ['N/A', 'July 5, 1978', 'Hot Lead and Cold Feet'],
 ['N/A', 'February 9, 1979', 'The North Avenue Irregulars'],
 ['N/A', ['June 27, 1979'], 'The Apple Dumpling Gang Rides Again'],
 [['July 19, 1979 (London)', 'August 3, 1979 (Los Angeles)'],
  'N/A',
  'Unidentified Flying Oddball'],
 [['December 18, 1979 (United Kingdom)', 'December 21, 1979 (United States)'],
  'N/A',
  'The Black Hole'],
 ['N/A', ['February 8, 1980'], 'Midnight Madness'],
 [['April 17, 1980 (New York City)', 'October 9, 1981 (U.S.)'],
  'N/A',
  'The Watcher in the Woods'],
 ['N/A', ['June 27, 1980'], 'Herbie Goes Bananas'],
 ['N/A', ['July 9, 1980 (Los Angeles)'], "The Last Flight of Noah's Ark"],
 [['December 6, 1980 ( Los Angeles )', 'December 12, 1980 ( United States )'],
  'N/A',
  'Popeye'],
 ['N/A', 'February 11, 1981 (Los Angeles)', 'The Devil and Max Devlin'],
 ['N/A', 'March 20, 1981', 'Amy'],
 ['N/A', ['June 26, 1981'], 'Dragonslayer'],
 ['N/A', ['July 10, 1981'], 'The Fox and the Hound'],
 ['N/A', ['August 7, 1981'], 'Condorman'],
 ['N/A', ['February 5, 1982'], 'Night Crossing'],
 ['N/A', ['July 9, 1982'], 'Tron'],
 ['N/A', 'July 30, 1982', 'Tex'],
 ['N/A', ['March 11, 1983'], 'Trenchcoat'],
 ['N/A',
  ['April 29, 1983 (United States)'],
  'Something Wicked This Way Comes'],
 [['October 7, 1983 (limited)', 'January 27, 1984 (release)'],
  'N/A',
  'Never Cry Wolf'],
 ['N/A', ['June 21, 1985 (United States)'], 'Return to Oz'],
 ['N/A', ['July 24, 1985'], 'The Black Cauldron'],
 ['N/A', ['September 27, 1985'], 'The Journey of Natty Gann'],
 ['N/A', ['November 22, 1985'], 'One Magic Christmas'],
 ['N/A', ['July 2, 1986'], 'The Great Mouse Detective'],
 ['N/A', ['August 1, 1986'], 'Flight of the Navigator'],
 ['N/A', ['June 5, 1987'], 'Benji the Hunted'],
 ['N/A', ['24 March 1988 (Australia)'], 'The Man from Snowy River II'],
 ['N/A', ['November 18, 1988'], 'Oliver & Company'],
 ['N/A', ['June 23, 1989'], 'Honey, I Shrunk the Kids'],
 ['N/A', 'August 18, 1989', 'Cheetah'],
 ['N/A', ['November 17, 1989'], 'The Little Mermaid'],
 ['N/A', ['August 3, 1990'], 'DuckTales the Movie: Treasure of the Lost Lamp'],
 ['N/A', ['November 16, 1990'], 'The Rescuers Down Under'],
 ['N/A', ['January 18, 1991'], 'White Fang'],
 [['3 October 1990'], 'N/A', 'Shipwrecked'],
 ['N/A', ['May 24, 1991'], "Wild Hearts Can't Be Broken"],
 ['N/A', ['June 21, 1991'], 'The Rocketeer'],
 [['September 29, 1991 ( NYFF )', 'November 13, 1991 (United States)'],
  'N/A',
  'Beauty and the Beast'],
 ['N/A', ['April 10, 1992'], 'Newsies'],
 ['N/A', ['July 17, 1992'], 'Honey, I Blew Up the Kid'],
 ['N/A', ['October 2, 1992'], 'The Mighty Ducks'],
 ['N/A', ['November 11, 1992'], 'Aladdin'],
 ['N/A', ['December 11, 1992'], 'The Muppet Christmas Carol'],
 ['N/A', 'February 3, 1993', 'Homeward Bound: The Incredible Journey'],
 ['N/A', ['March 12, 1993'], 'A Far Off Place'],
 ['N/A', ['April 2, 1993'], 'The Adventures of Huck Finn'],
 ['N/A', ['July 16, 1993'], 'Hocus Pocus'],
 ['N/A', ['October 1, 1993'], 'Cool Runnings'],
 ['N/A', ['November 12, 1993'], 'The Three Musketeers'],
 ['N/A', ['January 14, 1994'], 'Iron Will'],
 ['N/A', ['February 11, 1994'], 'Blank Check'],
 ['N/A', ['March 25, 1994'], 'D2: The Mighty Ducks'],
 ['N/A', ['April 14, 1994'], 'White Fang 2: Myth of the White Wolf'],
 ['N/A', ['June 15, 1994 (United States)'], 'The Lion King'],
 ['N/A', ['July 15, 1994'], 'Angels in the Outfield'],
 ['N/A', ['October 28, 1994'], "Squanto: A Warrior's Tale"],
 ['N/A', ['November 11, 1994'], 'The Santa Clause'],
 ['N/A', ['December 21, 1994'], "Rudyard Kipling's The Jungle Book"],
 ['N/A', ['February 17, 1995'], 'Heavyweights'],
 ['N/A', ['March 3, 1995'], 'Man of the House'],
 ['N/A', ['March 24, 1995'], 'Tall Tale'],
 ['N/A', ['April 7, 1995'], 'A Goofy Movie'],
 ['N/A', ['June 16, 1995 (United States)'], 'Pocahontas'],
 ['N/A', ['July 28, 1995'], 'Operation Dumbo Drop'],
 ['N/A', ['August 11, 1995'], "A Kid in King Arthur's Court"],
 ['N/A', ['September 27, 1995'], 'The Big Green'],
 [['January 22, 1995 ( Sundance Film Festival )', 'October 20, 1995 (U.S.)'],
  'N/A',
  'Frank and Ollie'],
 [['November 19, 1995 ( El Capitan Theatre )',
   'November 22, 1995 (United States)'],
  'N/A',
  'Toy Story'],
 ['N/A', ['December 22, 1995'], 'Tom and Huck'],
 ['N/A', ['February 16, 1996'], 'Muppet Treasure Island'],
 ['N/A', ['March 8, 1996'], 'Homeward Bound II: Lost in San Francisco'],
 [['April 12, 1996 (United States)', 'August 2, 1996 (United Kingdom)'],
  'N/A',
  'James and the Giant Peach'],
 [['June 19, 1996 (New Orleans)', 'June 21, 1996 (United States)'],
  'N/A',
  'The Hunchback of Notre Dame'],
 ['N/A', ['August 30, 1996'], 'First Kid'],
 ['N/A', ['October 4, 1996'], 'D3: The Mighty Ducks'],
 ['N/A', ['November 27, 1996 (United States)'], '101 Dalmatians'],
 ['N/A', ['February 14, 1997'], 'That Darn Cat'],
 [['March 7, 1997 (US)', 'August 5, 1997 (France)'], 'N/A', 'Jungle 2 Jungle'],
 ['N/A', 'March 18, 1997', 'Honey, We Shrunk Ourselves'],
 ['N/A', ['June 13, 1997 (United States)'], 'Hercules'],
 ['N/A', ['July 16, 1997'], 'George of the Jungle'],
 ['N/A', ['August 1, 1997'], 'Air Bud'],
 ['N/A', ['October 10, 1997'], 'RocketMan'],
 [['November 16, 1997 ( Pennsylvania )', 'November 26, 1997 (United States)'],
  'N/A',
  'Flubber'],
 ['N/A', ['December 25, 1997'], 'Mr. Magoo'],
 ['N/A', ['March 27, 1998 (United States)'], 'Meet the Deedles'],
 [['June 5, 1998 ( Hollywood Bowl )',
   'June 5, 1998',
   'June 19, 1998 (theatrical release)',
   'June 19, 1998'],
  'N/A',
  'Mulan'],
 ['N/A', ['July 29, 1998 (United States)'], 'The Parent Trap'],
 ['N/A', 'September 29, 1998', "The Jungle Book: Mowgli's Story"],
 ['N/A', ['November 13, 1998'], "I'll Be Home for Christmas"],
 ['N/A', ['November 20, 1998'], "A Bug's Life"],
 ['N/A', ['December 25, 1998'], 'Mighty Joe Young'],
 ['N/A', ['February 12, 1999'], 'My Favorite Martian'],
 ['N/A', ['March 26, 1999'], "Doug's 1st Movie"],
 ['N/A', ['May 14, 1999'], 'Endurance'],
 [['June 12, 1999 ( El Capitan Theatre )', 'June 16, 1999 (United States )'],
  'N/A',
  'Tarzan'],
 ['N/A', ['July 23, 1999'], 'Inspector Gadget'],
 [['May 1999 ( Cannes )', 'October 15, 1999 (United States)'],
  'N/A',
  'The Straight Story'],
 [['November 13, 1999 ( El Capitan Theatre )',
   'November 24, 1999 (United States)'],
  'N/A',
  'Toy Story 2'],
 ['N/A', 'February 11, 2000', 'The Tigger Movie'],
 ['N/A', ['March 10, 2000'], "Whispers: An Elephant's Tale"],
 ['N/A', ['May 19, 2000 (United States)'], 'Dinosaur'],
 [['December 17, 1999 (Premiere)',
   'January 1, 2000 ( IMAX )',
   'June 16, 2000 (United States)'],
  'N/A',
  'Fantasia 2000'],
 ['N/A', ['July 7, 2000'], 'The Kid'],
 ['N/A', ['September 19, 2000'], 'The Little Mermaid II: Return to the Sea'],
 ['N/A', ['September 29, 2000'], 'Remember the Titans'],
 ['N/A', ['November 22, 2000 (United States)'], '102 Dalmatians'],
 [['December 10, 2000 (premiere)', 'December 15, 2000 (United States)'],
  'N/A',
  "The Emperor's New Groove"],
 [['February 10, 2001 (premiere)', 'February 16, 2001 (United States)'],
  'N/A',
  "Recess: School's Out"],
 ['N/A', ['February 27, 2001'], "Lady and the Tramp II: Scamp's Adventure"],
 [['June 3, 2001 (premiere)', 'June 15, 2001 (United States)'],
  'N/A',
  'Atlantis: The Lost Empire'],
 [['July 29, 2001 ( El Capitan Theatre )', 'August 3, 2001 (United States)'],
  'N/A',
  'The Princess Diaries'],
 ['N/A', ['October 5, 2001'], "Max Keeble's Big Move"],
 [['October 28, 2001 ( El Capitan Theatre )',
   'November 2, 2001 (United States)'],
  'N/A',
  'Monsters, Inc.'],
 ['N/A',
  ['November 6, 2001'],
  "Mickey's Magical Christmas: Snowed in at the House of Mouse"],
 ['N/A', ['January 18, 2002'], 'Snow Dogs'],
 [['February 10, 2002 ( New York City )', 'February 15, 2002 (United States)'],
  'N/A',
  'Return to Never Land'],
 ['N/A', ['February 26, 2002'], 'Cinderella II: Dreams Come True'],
 ['N/A', ['March 19, 2002'], 'The Hunchback of Notre Dame II'],
 ['N/A', ['March 29, 2002'], 'The Rookie'],
 [['June 16, 2002 (premiere)', 'June 21, 2002'], 'N/A', 'Lilo & Stitch'],
 [['July 21, 2002', 'July 26, 2002'], 'N/A', 'The Country Bears'],
 ['N/A', ['20 July 2001 (Japan)'], 'Spirited Away'],
 ['N/A', ['October 11, 2002 (U.S.)'], 'Tuck Everlasting'],
 ['N/A', ['November 1, 2002'], 'The Santa Clause 2'],
 ['N/A', ['November 27, 2002'], 'Treasure Planet'],
 ['N/A', ['January 21, 2003'], "101 Dalmatians II: Patch's London Adventure"],
 ['N/A', ['February 14, 2003'], 'The Jungle Book 2'],
 ['N/A', ['March 11, 2003'], 'Inspector Gadget 2'],
 [['March 16, 2003 (Premiere)',
   'March 21, 2003 (United States)',
   'July 2, 2003 ( Manila , Philippines )'],
  'N/A',
  "Piglet's Big Movie"],
 [['March 31, 2003 (premiere)', 'April 11, 2003 (limited)'],
  'N/A',
  'Ghosts of the Abyss'],
 ['N/A', ['April 18, 2003 (United States)'], 'Holes'],
 ['N/A', ['May 2, 2003 (United States)'], 'The Lizzie McGuire Movie'],
 ['N/A', ['May 30, 2003'], 'Finding Nemo'],
 [['June 28, 2003 ( Disneyland Resort )', 'July 9, 2003 (United States)'],
  'N/A',
  'Pirates of the Caribbean: The Curse of the Black Pearl'],
 [['August 4, 2003 ( Los Angeles )', 'August 6, 2003 (United States)'],
  'N/A',
  'Freaky Friday'],
 ['N/A', ['August 26, 2003'], 'Stitch! The Movie'],
 ['N/A', ['October 21, 2003'], 'George of the Jungle 2'],
 ['N/A', ['November 1, 2003'], 'Brother Bear'],
 ['N/A', ['November 26, 2003'], 'The Haunted Mansion'],
 ['N/A', ['December 25, 2003'], 'The Young Black Stallion'],
 ['N/A', ['January 16, 2004'], "Teacher's Pet"],
 ['N/A', ['February 20, 2004'], 'Miracle'],
 ['N/A', ['February 10, 2004'], 'The Lion King 1½'],
 ['N/A',
  ['February 17, 2004 (United States)'],
  'Confessions of a Teenage Drama Queen'],
 ['N/A', ['March 9, 2004'], 'Winnie the Pooh: Springtime with Roo'],
 ['N/A', ['April 2, 2004'], 'Home on the Range'],
 ['N/A', ['April 22, 2004'], 'Sacred Planet'],
 ['N/A', ['June 16, 2004'], 'Around the World in 80 Days'],
 ['N/A', ['July 2, 2004'], "America's Heart and Soul"],
 ['N/A', ['August 11, 2004'], 'The Princess Diaries 2: Royal Engagement'],
 ['N/A', ['August 17, 2004'], 'Mickey, Donald, Goofy: The Three Musketeers'],
 [['October 24, 2004 ( El Capitan Theatre )',
   'November 5, 2004 (United States)'],
  'N/A',
  'The Incredibles'],
 ['N/A', ['November 9, 2004'], "Mickey's Twice Upon a Christmas"],
 ['N/A', ['November 19, 2004'], 'National Treasure'],
 ['N/A', ['January 28, 2005'], 'Aliens of the Deep'],
 [['November 3, 2004 (Italy)', 'February 1, 2005 (United States)'],
  'N/A',
  'Mulan II'],
 ['N/A', ['February 11, 2005'], "Pooh's Heffalump Movie"],
 ['N/A', ['March 4, 2005'], 'The Pacifier'],
 ['N/A', ['March 18, 2005'], 'Ice Princess'],
 ['N/A', ['June 14, 2005'], 'Tarzan II'],
 [['May 10, 2005 ( Las Vegas Motor Speedway )',

In [10]:
import re
from datetime import datetime

def date_convert(string):
  '''
  Get the datetime string 
  '''

  # pattern1 = r'(?P<month>[A-Z]\w*) (?P<date>\d{1,2}), (?P<year>\d{4})'
  # pattern2 = r'(?P<date>\d{1,2}) (?P<month>[A-Z]\w*) (?P<year>\d{4})'
  
  pattern1 = r'[A-Z]\w* \d{1,2}, \d{4}'
  pattern2 = r'\d{1,2} [A-Z]\w* \d{4}'
  pattern3 = r'\d{4}'
  match1 = re.search(pattern1, string)
  match2 = re.search(pattern2, string)
  match3 = re.search(pattern3, string)

  if match1 != None:
    date = datetime.strptime(match1.group(), '%B %d, %Y').strftime('%b %d, %Y')
    return date

  elif match2 != None:
    date = datetime.strptime(match2.group(), '%d %B %Y').strftime('%b %d, %Y')
    return date

  elif match3 != None:
    date = match3.group()
    return date
  
  # else:
  #   date = None
  #   return date


def get_date_string(string):

  if string in ['N/A', '', 'unknown']:
    return None
  
  if isinstance(string, list):
    for sub in string:
      date = date_convert(sub)
      if date != None:
        return date
      else:
        continue

  else:
    date = date_convert(string)
    return date

In [11]:
for movie in disney_data:
  try:
    if 'Release date' in movie.keys():
      movie['Release_date_converted'] = get_date_string(movie['Release date'])
    elif 'Release dates' in movie.keys():
      movie['Release_date_converted'] = get_date_string(movie['Release dates'])
    else:
      movie['Release_date_converted'] = None
  except Exception as e:
    print(e)
    print(movie['Title'])

In [12]:
[[movie.get('Release date', 'N/A'), movie.get('Release dates', 'N/A'), movie['Release_date_converted']] for movie in disney_data]

[[['May 19, 1937'], 'N/A', 'May 19, 1937'],
 ['N/A',
  ['December 21, 1937 ( Carthay Circle Theatre )',
   'February 4, 1938 (United States)'],
  'Dec 21, 1937'],
 ['N/A',
  ['February 7, 1940 ( Center Theatre )', 'February 23, 1940 (United States)'],
  'Feb 07, 1940'],
 [['November 13, 1940'], 'N/A', 'Nov 13, 1940'],
 [['June 27, 1941'], 'N/A', 'Jun 27, 1941'],
 ['N/A',
  ['October 23, 1941 (New York City)', 'October 31, 1941 (U.S.)'],
  'Oct 23, 1941'],
 ['N/A',
  ['August 9, 1942 (World Premiere – London)',
   'August 13, 1942 (Premiere – New York City)',
   'August 21, 1942 (U.S.)'],
  'Aug 09, 1942'],
 ['N/A',
  ['August 24, 1942 (World Premiere – Rio de Janeiro)',
   'February 6, 1943 (U.S. Premiere – Boston)',
   'February 19, 1943 (U.S.)'],
  'Aug 24, 1942'],
 [['July 17, 1943'], 'N/A', 'Jul 17, 1943'],
 ['N/A',
  ['December 21, 1944 (Mexico City)', 'February 3, 1945 (US)'],
  'Dec 21, 1944'],
 ['N/A',
  ['April 20, 1946 (New York City premiere)', 'August 15, 1946 (U.S.)'],
  'Apr 20, 1946'],
 ['N/A',
  ['November 12, 1946 (Premiere: Atlanta, Georgia)',
   'November 20, 1946',
   'March 30, 1947 (Stanford theater, Palo Alto, California)'],
  'Nov 12, 1946'],
 [['September 27, 1947'], 'N/A', 'Sep 27, 1947'],
 ['May 27, 1948', 'N/A', 'May 27, 1948'],
 ['N/A',
  ['November 29, 1948 (Chicago, Illinois)',
   'January 19, 1949 (Indianapolis, Indiana)'],
  'Nov 29, 1948'],
 [['October 5, 1949'], 'N/A', 'Oct 05, 1949'],
 ['N/A',
  ['February 15, 1950 (Boston)', 'March 4, 1950 (United States)'],
  'Feb 15, 1950'],
 ['N/A',
  ['June 22, 1950 (World Premiere-London)', 'July 30, 1950 (US)'],
  'Jun 22, 1950'],
 ['N/A',
  ['July 26, 1951 (London, premiere)',
   'July 28, 1951 (New York City, premiere)',
   'September 14, 1951 (United States)'],
  'Jul 26, 1951'],
 ['N/A',
  ['March 13, 1952 (Premiere- London )', 'June 26, 1952 ( US )'],
  'Mar 13, 1952'],
 [['February 5, 1953 (United States)'], 'N/A', 'Feb 05, 1953'],
 [['July 23, 1953 (US)'], 'N/A', 'Jul 23, 1953'],
 [['November 10, 1953'], 'N/A', 'Nov 10, 1953'],
 ['N/A',
  ['26 October 1953 (Premiere- London )', '27 February 1954 ( US )'],
  'Oct 26, 1953'],
 [['August 17, 1954'], 'N/A', 'Aug 17, 1954'],
 [['December 23, 1954'], 'N/A', 'Dec 23, 1954'],
 ['May 25, 1955', 'N/A', 'May 25, 1955'],
 [['June 22, 1955'], 'N/A', 'Jun 22, 1955'],
 [['September 14, 1955'], 'N/A', 'Sep 14, 1955'],
 ['December 22, 1955', 'N/A', 'Dec 22, 1955'],
 ['June 8, 1956', 'N/A', 'Jun 08, 1956'],
 ['July 18, 1956', 'N/A', 'Jul 18, 1956'],
 [['September 4, 1956'], 'N/A', 'Sep 04, 1956'],
 [['December 20, 1956'], 'N/A', 'Dec 20, 1956'],
 ['June 19, 1957', 'N/A', 'Jun 19, 1957'],
 ['August 28, 1957', 'N/A', 'Aug 28, 1957'],
 [['December 25, 1957'], 'N/A', 'Dec 25, 1957'],
 [['July 8, 1958'], 'N/A', 'Jul 08, 1958'],
 [['August 12, 1958'], 'N/A', 'Aug 12, 1958'],
 [['December 25, 1958'], 'N/A', 'Dec 25, 1958'],
 [['January 29, 1959'], 'N/A', 'Jan 29, 1959'],
 [['March 19, 1959'], 'N/A', 'Mar 19, 1959'],
 ['N/A',
  ['June 24, 1959 (Dublin)', 'June 26, 1959 (Los Angeles)'],
  'Jun 24, 1959'],
 ['N/A', 'N/A', None],
 [['November 10, 1959'], 'N/A', 'Nov 10, 1959'],
 ['January 21, 1960 ( Sarasota, FL )', 'N/A', 'Jan 21, 1960'],
 [['February 24, 1960'], 'N/A', 'Feb 24, 1960'],
 ['May 19, 1960', 'N/A', 'May 19, 1960'],
 ['N/A', 'N/A', None],
 ['N/A', ['June 1960 ( Berlin )', 'August 10, 1960 (US)'], '1960'],
 [['November 1, 1960'], 'N/A', 'Nov 01, 1960'],
 [['December 21, 1960'], 'N/A', 'Dec 21, 1960'],
 [['January 25, 1961'], 'N/A', 'Jan 25, 1961'],
 ['March 16, 1961', 'N/A', 'Mar 16, 1961'],
 [['June 21, 1961'], 'N/A', 'Jun 21, 1961'],
 [['July 12, 1961'], 'N/A', 'Jul 12, 1961'],
 [['July 17, 1961'], 'N/A', 'Jul 17, 1961'],
 [['December 14, 1961'], 'N/A', 'Dec 14, 1961'],
 ['April 5, 1962', 'N/A', 'Apr 05, 1962'],
 [['May 17, 1962'], 'N/A', 'May 17, 1962'],
 [['June 6, 1962'], 'N/A', 'Jun 06, 1962'],
 ['September 26, 1962', 'N/A', 'Sep 26, 1962'],
 [['November 7, 1962 (Los Angeles)'], 'N/A', 'Nov 07, 1962'],
 ['N/A',
  ['November 14, 1962 (London, premiere)', 'December 19, 1962 (US)'],
  'Nov 14, 1962'],
 [['January 16, 1963'], 'N/A', 'Jan 16, 1963'],
 [['March 29, 1963 (U.S.)'], 'N/A', 'Mar 29, 1963'],
 [['June 1, 1963'], 'N/A', 'Jun 01, 1963'],
 [['July 7, 1963'], 'N/A', 'Jul 07, 1963'],
 ['November 20, 1963', 'N/A', 'Nov 20, 1963'],
 [['December 25, 1963'], 'N/A', 'Dec 25, 1963'],
 [['March 12, 1964'], 'N/A', 'Mar 12, 1964'],
 [['February 11, 1964 (Los Angeles)'], 'N/A', 'Feb 11, 1964'],
 ['N/A',
  ['11 December 1963 ( New York City )', '4 June 1964 (U.S.)'],
  'Dec 11, 1963'],
 [['July 2, 1964'], 'N/A', 'Jul 02, 1964'],
 ['N/A', ['August 27, 1964 (LA)', 'September 24, 1964 (NY)'], 'Aug 27, 1964'],
 ['November 10, 1964', 'N/A', 'Nov 10, 1964'],
 [['December 18, 1964'], 'N/A', 'Dec 18, 1964'],
 [['August 18, 1965 (Los Angeles)'], 'N/A', 'Aug 18, 1965'],
 [['December 2, 1965'], 'N/A', 'Dec 02, 1965'],
 ['N/A',
  ['February 4, 1966 (premiere)', 'February 16, 1966 (United States)'],
  'Feb 04, 1966'],
 ['N/A',
  ['June 25, 1966 (San Diego)', 'June 29, 1966 (U.S.)'],
  'Jun 25, 1966'],
 ['October 1, 1966', 'N/A', 'Oct 01, 1966'],
 [['December 1, 1966'], 'N/A', 'Dec 01, 1966'],
 [['February 8, 1967 (San Francisco)'], 'N/A', 'Feb 08, 1967'],
 [['June 15, 1967'], 'N/A', 'Jun 15, 1967'],
 [['July 12, 1967'], 'N/A', 'Jul 12, 1967'],
 [['October 18, 1967'], 'N/A', 'Oct 18, 1967'],
 [['October 19, 1967'], 'N/A', 'Oct 19, 1967'],
 ['N/A', ['June 23, 1967', 'November 30, 1967'], 'Jun 23, 1967'],
 [['February 8, 1968'], 'N/A', 'Feb 08, 1968'],
 [['March 21, 1968 ( Radio City Music Hall )'], 'N/A', 'Mar 21, 1968'],
 [['June 26, 1968'], 'N/A', 'Jun 26, 1968'],
 [['December 3, 1968'], 'N/A', 'Dec 03, 1968'],
 ['N/A',
  ['December 24, 1968 (limited)', 'March 13, 1969 (wide)'],
  'Dec 24, 1968'],
 [['March 21, 1969'], 'N/A', 'Mar 21, 1969'],
 [['June 11, 1969'], 'N/A', 'Jun 11, 1969'],
 [['November 28, 1969'], 'N/A', 'Nov 28, 1969'],
 [['February 11, 1970'], 'N/A', 'Feb 11, 1970'],
 ['July 1, 1970', 'N/A', 'Jul 01, 1970'],
 ['N/A', ['December 15, 1970', 'January 20, 1971'], 'Dec 15, 1970'],
 ['N/A',
  ['December 11, 1970 (premiere)', 'December 24, 1970 (United States)'],
  'Dec 11, 1970'],
 ['March 17, 1971', 'N/A', 'Mar 17, 1971'],
 ['June 22, 1971', 'N/A', 'Jun 22, 1971'],
 [['June 30, 1971'], 'N/A', 'Jun 30, 1971'],
 [['October 7, 1971'], 'N/A', 'Oct 07, 1971'],
 [['March 22, 1972 (US)'], 'N/A', 'Mar 22, 1972'],
 ['July 12, 1972', 'N/A', 'Jul 12, 1972'],
 [['July 5, 1972'], 'N/A', 'Jul 05, 1972'],
 [['October 18, 1972'], 'N/A', 'Oct 18, 1972'],
 [['December 22, 1972'], 'N/A', 'Dec 22, 1972'],
 ['February 1, 1973', 'N/A', 'Feb 01, 1973'],
 [['March 23, 1973'], 'N/A', 'Mar 23, 1973'],
 [['June 20, 1973'], 'N/A', 'Jun 20, 1973'],
 [['November 8, 1973'], 'N/A', 'Nov 08, 1973'],
 [['December 14, 1973'], 'N/A', 'Dec 14, 1973'],
 [['June 6, 1974'], 'N/A', 'Jun 06, 1974'],
 [['July 31, 1974'], 'N/A', 'Jul 31, 1974'],
 [['August 1, 1974'], 'N/A', 'Aug 01, 1974'],
 ['December 20, 1974 (with Winnie the Pooh and Tigger Too )',
  'N/A',
  'Dec 20, 1974'],
 [['February 6, 1975'], 'N/A', 'Feb 06, 1975'],
 [['March 21, 1975 (United States)'], 'N/A', 'Mar 21, 1975'],
 [['July 1, 1975'], 'N/A', 'Jul 01, 1975'],
 [['July 9, 1975'], 'N/A', 'Jul 09, 1975'],
 [['October 8, 1975'], 'N/A', 'Oct 08, 1975'],
 [['1948–1960'], 'N/A', '1948'],
 ['December 25, 1975', 'N/A', 'Dec 25, 1975'],
 [['February 11, 1976 (Los Angeles)'], 'N/A', 'Feb 11, 1976'],
 [['July 1, 1976'], 'N/A', 'Jul 01, 1976'],
 [['July 7, 1976'], 'N/A', 'Jul 07, 1976'],
 [['December 16, 1976'], 'N/A', 'Dec 16, 1976'],
 [['December 17, 1976'], 'N/A', 'Dec 17, 1976'],
 ['N/A', ['May 26, 1976', '(UK)', 'March 11, 1977', '(US)'], 'May 26, 1976'],
 [['March 11, 1977'], 'N/A', 'Mar 11, 1977'],
 [['June 20, 1977'], 'N/A', 'Jun 20, 1977'],
 [['June 22, 1977'], 'N/A', 'Jun 22, 1977'],
 [['June 24, 1977'], 'N/A', 'Jun 24, 1977'],
 [['November 3, 1977'], 'N/A', 'Nov 03, 1977'],
 ['December 16, 1977', 'N/A', 'Dec 16, 1977'],
 [['March 10, 1978'], 'N/A', 'Mar 10, 1978'],
 [['June 30, 1978 (New York)'], 'N/A', 'Jun 30, 1978'],
 ['July 5, 1978', 'N/A', 'Jul 05, 1978'],
 ['February 9, 1979', 'N/A', 'Feb 09, 1979'],
 [['June 27, 1979'], 'N/A', 'Jun 27, 1979'],
 ['N/A',
  ['July 19, 1979 (London)', 'August 3, 1979 (Los Angeles)'],
  'Jul 19, 1979'],
 ['N/A',
  ['December 18, 1979 (United Kingdom)', 'December 21, 1979 (United States)'],
  'Dec 18, 1979'],
 [['February 8, 1980'], 'N/A', 'Feb 08, 1980'],
 ['N/A',
  ['April 17, 1980 (New York City)', 'October 9, 1981 (U.S.)'],
  'Apr 17, 1980'],
 [['June 27, 1980'], 'N/A', 'Jun 27, 1980'],
 [['July 9, 1980 (Los Angeles)'], 'N/A', 'Jul 09, 1980'],
 ['N/A',
  ['December 6, 1980 ( Los Angeles )', 'December 12, 1980 ( United States )'],
  'Dec 06, 1980'],
 ['February 11, 1981 (Los Angeles)', 'N/A', 'Feb 11, 1981'],
 ['March 20, 1981', 'N/A', 'Mar 20, 1981'],
 [['June 26, 1981'], 'N/A', 'Jun 26, 1981'],
 [['July 10, 1981'], 'N/A', 'Jul 10, 1981'],
 [['August 7, 1981'], 'N/A', 'Aug 07, 1981'],
 [['February 5, 1982'], 'N/A', 'Feb 05, 1982'],
 [['July 9, 1982'], 'N/A', 'Jul 09, 1982'],
 ['July 30, 1982', 'N/A', 'Jul 30, 1982'],
 [['March 11, 1983'], 'N/A', 'Mar 11, 1983'],
 [['April 29, 1983 (United States)'], 'N/A', 'Apr 29, 1983'],
 ['N/A',
  ['October 7, 1983 (limited)', 'January 27, 1984 (release)'],
  'Oct 07, 1983'],
 [['June 21, 1985 (United States)'], 'N/A', 'Jun 21, 1985'],
 [['July 24, 1985'], 'N/A', 'Jul 24, 1985'],
 [['September 27, 1985'], 'N/A', 'Sep 27, 1985'],
 [['November 22, 1985'], 'N/A', 'Nov 22, 1985'],
 [['July 2, 1986'], 'N/A', 'Jul 02, 1986'],
 [['August 1, 1986'], 'N/A', 'Aug 01, 1986'],
 [['June 5, 1987'], 'N/A', 'Jun 05, 1987'],
 [['24 March 1988 (Australia)'], 'N/A', 'Mar 24, 1988'],
 [['November 18, 1988'], 'N/A', 'Nov 18, 1988'],
 [['June 23, 1989'], 'N/A', 'Jun 23, 1989'],
 ['August 18, 1989', 'N/A', 'Aug 18, 1989'],
 [['November 17, 1989'], 'N/A', 'Nov 17, 1989'],
 [['August 3, 1990'], 'N/A', 'Aug 03, 1990'],
 [['November 16, 1990'], 'N/A', 'Nov 16, 1990'],
 [['January 18, 1991'], 'N/A', 'Jan 18, 1991'],
 ['N/A', ['3 October 1990'], 'Oct 03, 1990'],
 [['May 24, 1991'], 'N/A', 'May 24, 1991'],
 [['June 21, 1991'], 'N/A', 'Jun 21, 1991'],
 ['N/A',
  ['September 29, 1991 ( NYFF )', 'November 13, 1991 (United States)'],
  'Sep 29, 1991'],
 [['April 10, 1992'], 'N/A', 'Apr 10, 1992'],
 [['July 17, 1992'], 'N/A', 'Jul 17, 1992'],
 [['October 2, 1992'], 'N/A', 'Oct 02, 1992'],
 [['November 11, 1992'], 'N/A', 'Nov 11, 1992'],
 [['December 11, 1992'], 'N/A', 'Dec 11, 1992'],
 ['February 3, 1993', 'N/A', 'Feb 03, 1993'],
 [['March 12, 1993'], 'N/A', 'Mar 12, 1993'],
 [['April 2, 1993'], 'N/A', 'Apr 02, 1993'],
 [['July 16, 1993'], 'N/A', 'Jul 16, 1993'],
 [['October 1, 1993'], 'N/A', 'Oct 01, 1993'],
 [['November 12, 1993'], 'N/A', 'Nov 12, 1993'],
 [['January 14, 1994'], 'N/A', 'Jan 14, 1994'],
 [['February 11, 1994'], 'N/A', 'Feb 11, 1994'],
 [['March 25, 1994'], 'N/A', 'Mar 25, 1994'],
 [['April 14, 1994'], 'N/A', 'Apr 14, 1994'],
 [['June 15, 1994 (United States)'], 'N/A', 'Jun 15, 1994'],
 [['July 15, 1994'], 'N/A', 'Jul 15, 1994'],
 [['October 28, 1994'], 'N/A', 'Oct 28, 1994'],
 [['November 11, 1994'], 'N/A', 'Nov 11, 1994'],
 [['December 21, 1994'], 'N/A', 'Dec 21, 1994'],
 [['February 17, 1995'], 'N/A', 'Feb 17, 1995'],
 [['March 3, 1995'], 'N/A', 'Mar 03, 1995'],
 [['March 24, 1995'], 'N/A', 'Mar 24, 1995'],
 [['April 7, 1995'], 'N/A', 'Apr 07, 1995'],
 [['June 16, 1995 (United States)'], 'N/A', 'Jun 16, 1995'],
 [['July 28, 1995'], 'N/A', 'Jul 28, 1995'],
 [['August 11, 1995'], 'N/A', 'Aug 11, 1995'],
 [['September 27, 1995'], 'N/A', 'Sep 27, 1995'],
 ['N/A',
  ['January 22, 1995 ( Sundance Film Festival )', 'October 20, 1995 (U.S.)'],
  'Jan 22, 1995'],
 ['N/A',
  ['November 19, 1995 ( El Capitan Theatre )',
   'November 22, 1995 (United States)'],
  'Nov 19, 1995'],
 [['December 22, 1995'], 'N/A', 'Dec 22, 1995'],
 [['February 16, 1996'], 'N/A', 'Feb 16, 1996'],
 [['March 8, 1996'], 'N/A', 'Mar 08, 1996'],
 ['N/A',
  ['April 12, 1996 (United States)', 'August 2, 1996 (United Kingdom)'],
  'Apr 12, 1996'],
 ['N/A',
  ['June 19, 1996 (New Orleans)', 'June 21, 1996 (United States)'],
  'Jun 19, 1996'],
 [['August 30, 1996'], 'N/A', 'Aug 30, 1996'],
 [['October 4, 1996'], 'N/A', 'Oct 04, 1996'],
 [['November 27, 1996 (United States)'], 'N/A', 'Nov 27, 1996'],
 [['February 14, 1997'], 'N/A', 'Feb 14, 1997'],
 ['N/A', ['March 7, 1997 (US)', 'August 5, 1997 (France)'], 'Mar 07, 1997'],
 ['March 18, 1997', 'N/A', 'Mar 18, 1997'],
 [['June 13, 1997 (United States)'], 'N/A', 'Jun 13, 1997'],
 [['July 16, 1997'], 'N/A', 'Jul 16, 1997'],
 [['August 1, 1997'], 'N/A', 'Aug 01, 1997'],
 [['October 10, 1997'], 'N/A', 'Oct 10, 1997'],
 ['N/A',
  ['November 16, 1997 ( Pennsylvania )', 'November 26, 1997 (United States)'],
  'Nov 16, 1997'],
 [['December 25, 1997'], 'N/A', 'Dec 25, 1997'],
 [['March 27, 1998 (United States)'], 'N/A', 'Mar 27, 1998'],
 ['N/A',
  ['June 5, 1998 ( Hollywood Bowl )',
   'June 5, 1998',
   'June 19, 1998 (theatrical release)',
   'June 19, 1998'],
  'Jun 05, 1998'],
 [['July 29, 1998 (United States)'], 'N/A', 'Jul 29, 1998'],
 ['September 29, 1998', 'N/A', 'Sep 29, 1998'],
 [['November 13, 1998'], 'N/A', 'Nov 13, 1998'],
 [['November 20, 1998'], 'N/A', 'Nov 20, 1998'],
 [['December 25, 1998'], 'N/A', 'Dec 25, 1998'],
 [['February 12, 1999'], 'N/A', 'Feb 12, 1999'],
 [['March 26, 1999'], 'N/A', 'Mar 26, 1999'],
 [['May 14, 1999'], 'N/A', 'May 14, 1999'],
 ['N/A',
  ['June 12, 1999 ( El Capitan Theatre )', 'June 16, 1999 (United States )'],
  'Jun 12, 1999'],
 [['July 23, 1999'], 'N/A', 'Jul 23, 1999'],
 ['N/A', ['May 1999 ( Cannes )', 'October 15, 1999 (United States)'], '1999'],
 ['N/A',
  ['November 13, 1999 ( El Capitan Theatre )',
   'November 24, 1999 (United States)'],
  'Nov 13, 1999'],
 ['February 11, 2000', 'N/A', 'Feb 11, 2000'],
 [['March 10, 2000'], 'N/A', 'Mar 10, 2000'],
 [['May 19, 2000 (United States)'], 'N/A', 'May 19, 2000'],
 ['N/A',
  ['December 17, 1999 (Premiere)',
   'January 1, 2000 ( IMAX )',
   'June 16, 2000 (United States)'],
  'Dec 17, 1999'],
 [['July 7, 2000'], 'N/A', 'Jul 07, 2000'],
 [['September 19, 2000'], 'N/A', 'Sep 19, 2000'],
 [['September 29, 2000'], 'N/A', 'Sep 29, 2000'],
 [['November 22, 2000 (United States)'], 'N/A', 'Nov 22, 2000'],
 ['N/A',
  ['December 10, 2000 (premiere)', 'December 15, 2000 (United States)'],
  'Dec 10, 2000'],
 ['N/A',
  ['February 10, 2001 (premiere)', 'February 16, 2001 (United States)'],
  'Feb 10, 2001'],
 [['February 27, 2001'], 'N/A', 'Feb 27, 2001'],
 ['N/A',
  ['June 3, 2001 (premiere)', 'June 15, 2001 (United States)'],
  'Jun 03, 2001'],
 ['N/A',
  ['July 29, 2001 ( El Capitan Theatre )', 'August 3, 2001 (United States)'],
  'Jul 29, 2001'],
 [['October 5, 2001'], 'N/A', 'Oct 05, 2001'],
 ['N/A',
  ['October 28, 2001 ( El Capitan Theatre )',
   'November 2, 2001 (United States)'],
  'Oct 28, 2001'],
 [['November 6, 2001'], 'N/A', 'Nov 06, 2001'],
 [['January 18, 2002'], 'N/A', 'Jan 18, 2002'],
 ['N/A',
  ['February 10, 2002 ( New York City )', 'February 15, 2002 (United States)'],
  'Feb 10, 2002'],
 [['February 26, 2002'], 'N/A', 'Feb 26, 2002'],
 [['March 19, 2002'], 'N/A', 'Mar 19, 2002'],
 [['March 29, 2002'], 'N/A', 'Mar 29, 2002'],
 ['N/A', ['June 16, 2002 (premiere)', 'June 21, 2002'], 'Jun 16, 2002'],
 ['N/A', ['July 21, 2002', 'July 26, 2002'], 'Jul 21, 2002'],
 [['20 July 2001 (Japan)'], 'N/A', 'Jul 20, 2001'],
 [['October 11, 2002 (U.S.)'], 'N/A', 'Oct 11, 2002'],
 [['November 1, 2002'], 'N/A', 'Nov 01, 2002'],
 [['November 27, 2002'], 'N/A', 'Nov 27, 2002'],
 [['January 21, 2003'], 'N/A', 'Jan 21, 2003'],
 [['February 14, 2003'], 'N/A', 'Feb 14, 2003'],
 [['March 11, 2003'], 'N/A', 'Mar 11, 2003'],
 ['N/A',
  ['March 16, 2003 (Premiere)',
   'March 21, 2003 (United States)',
   'July 2, 2003 ( Manila , Philippines )'],
  'Mar 16, 2003'],
 ['N/A',
  ['March 31, 2003 (premiere)', 'April 11, 2003 (limited)'],
  'Mar 31, 2003'],
 [['April 18, 2003 (United States)'], 'N/A', 'Apr 18, 2003'],
 [['May 2, 2003 (United States)'], 'N/A', 'May 02, 2003'],
 [['May 30, 2003'], 'N/A', 'May 30, 2003'],
 ['N/A',
  ['June 28, 2003 ( Disneyland Resort )', 'July 9, 2003 (United States)'],
  'Jun 28, 2003'],
 ['N/A',
  ['August 4, 2003 ( Los Angeles )', 'August 6, 2003 (United States)'],
  'Aug 04, 2003'],
 [['August 26, 2003'], 'N/A', 'Aug 26, 2003'],
 [['October 21, 2003'], 'N/A', 'Oct 21, 2003'],
 [['November 1, 2003'], 'N/A', 'Nov 01, 2003'],
 [['November 26, 2003'], 'N/A', 'Nov 26, 2003'],
 [['December 25, 2003'], 'N/A', 'Dec 25, 2003'],
 [['January 16, 2004'], 'N/A', 'Jan 16, 2004'],
 [['February 20, 2004'], 'N/A', 'Feb 20, 2004'],
 [['February 10, 2004'], 'N/A', 'Feb 10, 2004'],
 [['February 17, 2004 (United States)'], 'N/A', 'Feb 17, 2004'],
 [['March 9, 2004'], 'N/A', 'Mar 09, 2004'],
 [['April 2, 2004'], 'N/A', 'Apr 02, 2004'],
 [['April 22, 2004'], 'N/A', 'Apr 22, 2004'],
 [['June 16, 2004'], 'N/A', 'Jun 16, 2004'],
 [['July 2, 2004'], 'N/A', 'Jul 02, 2004'],
 [['August 11, 2004'], 'N/A', 'Aug 11, 2004'],
 [['August 17, 2004'], 'N/A', 'Aug 17, 2004'],
 ['N/A',
  ['October 24, 2004 ( El Capitan Theatre )',
   'November 5, 2004 (United States)'],
  'Oct 24, 2004'],
 [['November 9, 2004'], 'N/A', 'Nov 09, 2004'],
 [['November 19, 2004'], 'N/A', 'Nov 19, 2004'],
 [['January 28, 2005'], 'N/A', 'Jan 28, 2005'],
 ['N/A',
  ['November 3, 2004 (Italy)', 'February 1, 2005 (United States)'],
  'Nov 03, 2004'],
 [['February 11, 2005'], 'N/A', 'Feb 11, 2005'],
 [['March 4, 2005'], 'N/A', 'Mar 04, 2005'],
 [['March 18, 2005'], 'N/A', 'Mar 18, 2005'],
 [['June 14, 2005'], 'N/A', 'Jun 14, 2005'],
 ['N/A',
  ['May 10, 2005 ( Las Vegas Motor Speedway )',
   'June 22, 2005 (United States)'],
  'May 10, 2005'],
 ['N/A',
  ['5 September 2004 ( Venice )', '20 November 2004 (Japan)'],
  'Sep 05, 2004'],
 [['July 29, 2005'], 'N/A', 'Jul 29, 2005'],
 ['N/A', ['March 25, 2005 (UK)', 'August 19, 2005 (US)'], 'Mar 25, 2005'],
 [['August 30, 2005'], 'N/A', 'Aug 30, 2005'],
 [['September 13, 2005'], 'N/A', 'Sep 13, 2005'],
 [['September 30, 2005'], 'N/A', 'Sep 30, 2005'],
 ['N/A',
  ['October 30, 2005 ( El Capitan Theatre )',
   'November 4, 2005 (United States)'],
  'Oct 30, 2005'],
 ['N/A',
  ['December 7, 2005 ( Royal Film Performance )',
   'December 8, 2005 (United Kingdom)',
   'December 9, 2005 (United States)'],
  'Dec 07, 2005'],
 ['December 13, 2005', 'N/A', 'Dec 13, 2005'],
 ['January 13, 2006', 'N/A', 'Jan 13, 2006'],
 [['January 27, 2006'], 'N/A', 'Jan 27, 2006'],
 ['N/A',
  ['January 26, 2006 (Argentina)', 'February 7, 2006 (United States)'],
  'Jan 26, 2006'],
 [['February 17, 2006 (United States)'], 'N/A', 'Feb 17, 2006'],
 [['March 10, 2006'], 'N/A', 'Mar 10, 2006'],
 [['April 14, 2006'], 'N/A', 'Apr 14, 2006'],
 ['N/A',
  ["May 26, 2006 ( Lowe's Motor Speedway )", 'June 9, 2006 (United States)'],
  'May 26, 2006'],
 ['N/A', ['June 23, 2006', 'June 27, 2006'], 'Jun 23, 2006'],
 ['N/A',
  ['June 16, 2006 ( Disneyland Resort )', 'June 16, 2006 (United States)'],
  'Jun 16, 2006'],
 [['August 25, 2006'], 'N/A', 'Aug 25, 2006'],
 [['August 29, 2006'], 'N/A', 'Aug 29, 2006'],
 ['N/A',
  ['October 13, 1993 (limited)', 'October 29, 1993 (United States)'],
  'Oct 13, 1993'],
 [['November 3, 2006'], 'N/A', 'Nov 03, 2006'],
 [['December 12, 2006'], 'N/A', 'Dec 12, 2006'],
 [['February 6, 2007'], 'N/A', 'Feb 06, 2007'],
 [['February 16, 2007'], 'N/A', 'Feb 16, 2007'],
 ['N/A',
  ['March 23, 2007 (United Kingdom)', 'March 30, 2007 (United States)'],
  'Mar 23, 2007'],
 ['N/A',
  ['May 19, 2007 ( Disneyland Resort )', 'May 25, 2007 (United States)'],
  'May 19, 2007'],
 ['N/A',
  ['June 22, 2007 ( Kodak Theatre )', 'June 29, 2007 (United States)'],
  'Jun 22, 2007'],
 ['N/A',
  ['June 29, 2007 (China)', 'January 26, 2009 (United States)'],
  'Jun 29, 2007'],
 [['August 3, 2007'], 'N/A', 'Aug 03, 2007'],
 [['August 28, 2007'], 'N/A', 'Aug 28, 2007'],